/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.anniversary.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the anniversarywish service. Represents a row in the &quot;add_anniversarywish&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.anniversary.model.impl.anniversarywishModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.anniversary.model.impl.anniversarywishImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see anniversarywish
 * @see com.chola.anniversary.model.impl.anniversarywishImpl
 * @see com.chola.anniversary.model.impl.anniversarywishModelImpl
 * @generated
 */
@ProviderType
public interface anniversarywishModel extends BaseModel<anniversarywish> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a anniversarywish model instance should use the {@link anniversarywish} interface instead.
	 */

	/**
	 * Returns the primary key of this anniversarywish.
	 *
	 * @return the primary key of this anniversarywish
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this anniversarywish.
	 *
	 * @param primaryKey the primary key of this anniversarywish
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this anniversarywish.
	 *
	 * @return the ID of this anniversarywish
	 */
	public long getId();

	/**
	 * Sets the ID of this anniversarywish.
	 *
	 * @param id the ID of this anniversarywish
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this anniversarywish.
	 *
	 * @return the user ID of this anniversarywish
	 */
	@AutoEscape
	public String getUserId();

	/**
	 * Sets the user ID of this anniversarywish.
	 *
	 * @param userId the user ID of this anniversarywish
	 */
	public void setUserId(String userId);

	/**
	 * Returns the wished by of this anniversarywish.
	 *
	 * @return the wished by of this anniversarywish
	 */
	@AutoEscape
	public String getWishedBy();

	/**
	 * Sets the wished by of this anniversarywish.
	 *
	 * @param wishedBy the wished by of this anniversarywish
	 */
	public void setWishedBy(String wishedBy);

	/**
	 * Returns the message of this anniversarywish.
	 *
	 * @return the message of this anniversarywish
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this anniversarywish.
	 *
	 * @param message the message of this anniversarywish
	 */
	public void setMessage(String message);

	/**
	 * Returns the created date of this anniversarywish.
	 *
	 * @return the created date of this anniversarywish
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this anniversarywish.
	 *
	 * @param createdDate the created date of this anniversarywish
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.anniversary.model.anniversarywish anniversarywish);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.anniversary.model.anniversarywish> toCacheModel();

	@Override
	public com.chola.anniversary.model.anniversarywish toEscapedModel();

	@Override
	public com.chola.anniversary.model.anniversarywish toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}