/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.swagatam.service.base;

import com.chola.swagatam.model.swagatampath;
import com.chola.swagatam.service.persistence.swagatamPersistence;
import com.chola.swagatam.service.persistence.swagatamdataFinder;
import com.chola.swagatam.service.persistence.swagatamdataPersistence;
import com.chola.swagatam.service.persistence.swagatampathPersistence;
import com.chola.swagatam.service.swagatampathService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the swagatampath remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.chola.swagatam.service.impl.swagatampathServiceImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see com.chola.swagatam.service.impl.swagatampathServiceImpl
 * @see com.chola.swagatam.service.swagatampathServiceUtil
 * @generated
 */
public abstract class swagatampathServiceBaseImpl extends BaseServiceImpl
	implements swagatampathService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.chola.swagatam.service.swagatampathServiceUtil} to access the swagatampath remote service.
	 */

	/**
	 * Returns the swagatam local service.
	 *
	 * @return the swagatam local service
	 */
	public com.chola.swagatam.service.swagatamLocalService getswagatamLocalService() {
		return swagatamLocalService;
	}

	/**
	 * Sets the swagatam local service.
	 *
	 * @param swagatamLocalService the swagatam local service
	 */
	public void setswagatamLocalService(
		com.chola.swagatam.service.swagatamLocalService swagatamLocalService) {
		this.swagatamLocalService = swagatamLocalService;
	}

	/**
	 * Returns the swagatam remote service.
	 *
	 * @return the swagatam remote service
	 */
	public com.chola.swagatam.service.swagatamService getswagatamService() {
		return swagatamService;
	}

	/**
	 * Sets the swagatam remote service.
	 *
	 * @param swagatamService the swagatam remote service
	 */
	public void setswagatamService(
		com.chola.swagatam.service.swagatamService swagatamService) {
		this.swagatamService = swagatamService;
	}

	/**
	 * Returns the swagatam persistence.
	 *
	 * @return the swagatam persistence
	 */
	public swagatamPersistence getswagatamPersistence() {
		return swagatamPersistence;
	}

	/**
	 * Sets the swagatam persistence.
	 *
	 * @param swagatamPersistence the swagatam persistence
	 */
	public void setswagatamPersistence(swagatamPersistence swagatamPersistence) {
		this.swagatamPersistence = swagatamPersistence;
	}

	/**
	 * Returns the swagatamdata local service.
	 *
	 * @return the swagatamdata local service
	 */
	public com.chola.swagatam.service.swagatamdataLocalService getswagatamdataLocalService() {
		return swagatamdataLocalService;
	}

	/**
	 * Sets the swagatamdata local service.
	 *
	 * @param swagatamdataLocalService the swagatamdata local service
	 */
	public void setswagatamdataLocalService(
		com.chola.swagatam.service.swagatamdataLocalService swagatamdataLocalService) {
		this.swagatamdataLocalService = swagatamdataLocalService;
	}

	/**
	 * Returns the swagatamdata remote service.
	 *
	 * @return the swagatamdata remote service
	 */
	public com.chola.swagatam.service.swagatamdataService getswagatamdataService() {
		return swagatamdataService;
	}

	/**
	 * Sets the swagatamdata remote service.
	 *
	 * @param swagatamdataService the swagatamdata remote service
	 */
	public void setswagatamdataService(
		com.chola.swagatam.service.swagatamdataService swagatamdataService) {
		this.swagatamdataService = swagatamdataService;
	}

	/**
	 * Returns the swagatamdata persistence.
	 *
	 * @return the swagatamdata persistence
	 */
	public swagatamdataPersistence getswagatamdataPersistence() {
		return swagatamdataPersistence;
	}

	/**
	 * Sets the swagatamdata persistence.
	 *
	 * @param swagatamdataPersistence the swagatamdata persistence
	 */
	public void setswagatamdataPersistence(
		swagatamdataPersistence swagatamdataPersistence) {
		this.swagatamdataPersistence = swagatamdataPersistence;
	}

	/**
	 * Returns the swagatamdata finder.
	 *
	 * @return the swagatamdata finder
	 */
	public swagatamdataFinder getswagatamdataFinder() {
		return swagatamdataFinder;
	}

	/**
	 * Sets the swagatamdata finder.
	 *
	 * @param swagatamdataFinder the swagatamdata finder
	 */
	public void setswagatamdataFinder(swagatamdataFinder swagatamdataFinder) {
		this.swagatamdataFinder = swagatamdataFinder;
	}

	/**
	 * Returns the swagatampath local service.
	 *
	 * @return the swagatampath local service
	 */
	public com.chola.swagatam.service.swagatampathLocalService getswagatampathLocalService() {
		return swagatampathLocalService;
	}

	/**
	 * Sets the swagatampath local service.
	 *
	 * @param swagatampathLocalService the swagatampath local service
	 */
	public void setswagatampathLocalService(
		com.chola.swagatam.service.swagatampathLocalService swagatampathLocalService) {
		this.swagatampathLocalService = swagatampathLocalService;
	}

	/**
	 * Returns the swagatampath remote service.
	 *
	 * @return the swagatampath remote service
	 */
	public swagatampathService getswagatampathService() {
		return swagatampathService;
	}

	/**
	 * Sets the swagatampath remote service.
	 *
	 * @param swagatampathService the swagatampath remote service
	 */
	public void setswagatampathService(swagatampathService swagatampathService) {
		this.swagatampathService = swagatampathService;
	}

	/**
	 * Returns the swagatampath persistence.
	 *
	 * @return the swagatampath persistence
	 */
	public swagatampathPersistence getswagatampathPersistence() {
		return swagatampathPersistence;
	}

	/**
	 * Sets the swagatampath persistence.
	 *
	 * @param swagatampathPersistence the swagatampath persistence
	 */
	public void setswagatampathPersistence(
		swagatampathPersistence swagatampathPersistence) {
		this.swagatampathPersistence = swagatampathPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return swagatampathService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return swagatampath.class;
	}

	protected String getModelClassName() {
		return swagatampath.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = swagatampathPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.chola.swagatam.service.swagatamLocalService.class)
	protected com.chola.swagatam.service.swagatamLocalService swagatamLocalService;
	@BeanReference(type = com.chola.swagatam.service.swagatamService.class)
	protected com.chola.swagatam.service.swagatamService swagatamService;
	@BeanReference(type = swagatamPersistence.class)
	protected swagatamPersistence swagatamPersistence;
	@BeanReference(type = com.chola.swagatam.service.swagatamdataLocalService.class)
	protected com.chola.swagatam.service.swagatamdataLocalService swagatamdataLocalService;
	@BeanReference(type = com.chola.swagatam.service.swagatamdataService.class)
	protected com.chola.swagatam.service.swagatamdataService swagatamdataService;
	@BeanReference(type = swagatamdataPersistence.class)
	protected swagatamdataPersistence swagatamdataPersistence;
	@BeanReference(type = swagatamdataFinder.class)
	protected swagatamdataFinder swagatamdataFinder;
	@BeanReference(type = com.chola.swagatam.service.swagatampathLocalService.class)
	protected com.chola.swagatam.service.swagatampathLocalService swagatampathLocalService;
	@BeanReference(type = swagatampathService.class)
	protected swagatampathService swagatampathService;
	@BeanReference(type = swagatampathPersistence.class)
	protected swagatampathPersistence swagatampathPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private swagatampathServiceClpInvoker _clpInvoker = new swagatampathServiceClpInvoker();
}