/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.notificationchannel.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the NoticationCategoryCount service. Represents a row in the &quot;channel_NoticationCategoryCount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.notificationchannel.model.impl.NoticationCategoryCountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.notificationchannel.model.impl.NoticationCategoryCountImpl}.
 * </p>
 *
 * @author cloverliferay01
 * @see NoticationCategoryCount
 * @see com.chola.notificationchannel.model.impl.NoticationCategoryCountImpl
 * @see com.chola.notificationchannel.model.impl.NoticationCategoryCountModelImpl
 * @generated
 */
@ProviderType
public interface NoticationCategoryCountModel extends BaseModel<NoticationCategoryCount> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notication category count model instance should use the {@link NoticationCategoryCount} interface instead.
	 */

	/**
	 * Returns the primary key of this notication category count.
	 *
	 * @return the primary key of this notication category count
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notication category count.
	 *
	 * @param primaryKey the primary key of this notication category count
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event ID of this notication category count.
	 *
	 * @return the event ID of this notication category count
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this notication category count.
	 *
	 * @param eventId the event ID of this notication category count
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the username of this notication category count.
	 *
	 * @return the username of this notication category count
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this notication category count.
	 *
	 * @param username the username of this notication category count
	 */
	public void setUsername(String username);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(NoticationCategoryCount noticationCategoryCount);

	@Override
	public int hashCode();

	@Override
	public CacheModel<NoticationCategoryCount> toCacheModel();

	@Override
	public NoticationCategoryCount toEscapedModel();

	@Override
	public NoticationCategoryCount toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}