/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.branchdetails.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the branchdetails service. Represents a row in the &quot;branch_branchdetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.branchdetails.model.impl.branchdetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.branchdetails.model.impl.branchdetailsImpl}.
 * </p>
 *
 * @author adms.java1
 * @see branchdetails
 * @see com.branchdetails.model.impl.branchdetailsImpl
 * @see com.branchdetails.model.impl.branchdetailsModelImpl
 * @generated
 */
@ProviderType
public interface branchdetailsModel extends BaseModel<branchdetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a branchdetails model instance should use the {@link branchdetails} interface instead.
	 */

	/**
	 * Returns the primary key of this branchdetails.
	 *
	 * @return the primary key of this branchdetails
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this branchdetails.
	 *
	 * @param primaryKey the primary key of this branchdetails
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the branch_id of this branchdetails.
	 *
	 * @return the branch_id of this branchdetails
	 */
	public long getBranch_id();

	/**
	 * Sets the branch_id of this branchdetails.
	 *
	 * @param branch_id the branch_id of this branchdetails
	 */
	public void setBranch_id(long branch_id);

	/**
	 * Returns the branch_code of this branchdetails.
	 *
	 * @return the branch_code of this branchdetails
	 */
	@AutoEscape
	public String getBranch_code();

	/**
	 * Sets the branch_code of this branchdetails.
	 *
	 * @param branch_code the branch_code of this branchdetails
	 */
	public void setBranch_code(String branch_code);

	/**
	 * Returns the branch_address of this branchdetails.
	 *
	 * @return the branch_address of this branchdetails
	 */
	@AutoEscape
	public String getBranch_address();

	/**
	 * Sets the branch_address of this branchdetails.
	 *
	 * @param branch_address the branch_address of this branchdetails
	 */
	public void setBranch_address(String branch_address);

	/**
	 * Returns the city_id of this branchdetails.
	 *
	 * @return the city_id of this branchdetails
	 */
	public long getCity_id();

	/**
	 * Sets the city_id of this branchdetails.
	 *
	 * @param city_id the city_id of this branchdetails
	 */
	public void setCity_id(long city_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.branchdetails.model.branchdetails branchdetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.branchdetails.model.branchdetails> toCacheModel();

	@Override
	public com.branchdetails.model.branchdetails toEscapedModel();

	@Override
	public com.branchdetails.model.branchdetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}