/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.customer.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the customer service. Represents a row in the &quot;Z_customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.customer.model.impl.customerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.customer.model.impl.customerImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see customer
 * @see com.customer.model.impl.customerImpl
 * @see com.customer.model.impl.customerModelImpl
 * @generated
 */
@ProviderType
public interface customerModel extends BaseModel<customer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer model instance should use the {@link customer} interface instead.
	 */

	/**
	 * Returns the primary key of this customer.
	 *
	 * @return the primary key of this customer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer.
	 *
	 * @param primaryKey the primary key of this customer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the customer ID of this customer.
	 *
	 * @return the customer ID of this customer
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this customer.
	 *
	 * @param customerId the customer ID of this customer
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the name of this customer.
	 *
	 * @return the name of this customer
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this customer.
	 *
	 * @param name the name of this customer
	 */
	public void setName(String name);

	/**
	 * Returns the product of this customer.
	 *
	 * @return the product of this customer
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this customer.
	 *
	 * @param product the product of this customer
	 */
	public void setProduct(String product);

	/**
	 * Returns the phone no of this customer.
	 *
	 * @return the phone no of this customer
	 */
	public int getPhoneNo();

	/**
	 * Sets the phone no of this customer.
	 *
	 * @param PhoneNo the phone no of this customer
	 */
	public void setPhoneNo(int PhoneNo);

	/**
	 * Returns the price of this customer.
	 *
	 * @return the price of this customer
	 */
	public float getPrice();

	/**
	 * Sets the price of this customer.
	 *
	 * @param price the price of this customer
	 */
	public void setPrice(float price);

	/**
	 * Returns the email of this customer.
	 *
	 * @return the email of this customer
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this customer.
	 *
	 * @param email the email of this customer
	 */
	public void setEmail(String email);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.customer.model.customer customer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.customer.model.customer> toCacheModel();

	@Override
	public com.customer.model.customer toEscapedModel();

	@Override
	public com.customer.model.customer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}