/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.productbuysell.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BuySellProducts service. Represents a row in the &quot;chola_BuySellProducts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.productbuysell.model.impl.BuySellProductsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.productbuysell.model.impl.BuySellProductsImpl}.
 * </p>
 *
 * @author CloverLiferay03
 * @see BuySellProducts
 * @see com.chola.productbuysell.model.impl.BuySellProductsImpl
 * @see com.chola.productbuysell.model.impl.BuySellProductsModelImpl
 * @generated
 */
@ProviderType
public interface BuySellProductsModel extends BaseModel<BuySellProducts> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a buy sell products model instance should use the {@link BuySellProducts} interface instead.
	 */

	/**
	 * Returns the primary key of this buy sell products.
	 *
	 * @return the primary key of this buy sell products
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this buy sell products.
	 *
	 * @param primaryKey the primary key of this buy sell products
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this buy sell products.
	 *
	 * @return the ID of this buy sell products
	 */
	public long getId();

	/**
	 * Sets the ID of this buy sell products.
	 *
	 * @param id the ID of this buy sell products
	 */
	public void setId(long id);

	/**
	 * Returns the seller name of this buy sell products.
	 *
	 * @return the seller name of this buy sell products
	 */
	@AutoEscape
	public String getSellerName();

	/**
	 * Sets the seller name of this buy sell products.
	 *
	 * @param sellerName the seller name of this buy sell products
	 */
	public void setSellerName(String sellerName);

	/**
	 * Returns the contact number of this buy sell products.
	 *
	 * @return the contact number of this buy sell products
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this buy sell products.
	 *
	 * @param contactNumber the contact number of this buy sell products
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the content_id of this buy sell products.
	 *
	 * @return the content_id of this buy sell products
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this buy sell products.
	 *
	 * @param content_id the content_id of this buy sell products
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the category_id of this buy sell products.
	 *
	 * @return the category_id of this buy sell products
	 */
	public long getCategory_id();

	/**
	 * Sets the category_id of this buy sell products.
	 *
	 * @param category_id the category_id of this buy sell products
	 */
	public void setCategory_id(long category_id);

	/**
	 * Returns the title of this buy sell products.
	 *
	 * @return the title of this buy sell products
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this buy sell products.
	 *
	 * @param title the title of this buy sell products
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this buy sell products.
	 *
	 * @return the description of this buy sell products
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this buy sell products.
	 *
	 * @param description the description of this buy sell products
	 */
	public void setDescription(String description);

	/**
	 * Returns the asking price of this buy sell products.
	 *
	 * @return the asking price of this buy sell products
	 */
	@AutoEscape
	public String getAskingPrice();

	/**
	 * Sets the asking price of this buy sell products.
	 *
	 * @param askingPrice the asking price of this buy sell products
	 */
	public void setAskingPrice(String askingPrice);

	/**
	 * Returns the user screen name of this buy sell products.
	 *
	 * @return the user screen name of this buy sell products
	 */
	@AutoEscape
	public String getUserScreenName();

	/**
	 * Sets the user screen name of this buy sell products.
	 *
	 * @param userScreenName the user screen name of this buy sell products
	 */
	public void setUserScreenName(String userScreenName);

	/**
	 * Returns the location of this buy sell products.
	 *
	 * @return the location of this buy sell products
	 */
	public long getLocation();

	/**
	 * Sets the location of this buy sell products.
	 *
	 * @param location the location of this buy sell products
	 */
	public void setLocation(long location);

	/**
	 * Returns the status of this buy sell products.
	 *
	 * @return the status of this buy sell products
	 */
	public long getStatus();

	/**
	 * Sets the status of this buy sell products.
	 *
	 * @param status the status of this buy sell products
	 */
	public void setStatus(long status);

	/**
	 * Returns the approvedstatus of this buy sell products.
	 *
	 * @return the approvedstatus of this buy sell products
	 */
	public long getApprovedstatus();

	/**
	 * Sets the approvedstatus of this buy sell products.
	 *
	 * @param approvedstatus the approvedstatus of this buy sell products
	 */
	public void setApprovedstatus(long approvedstatus);

	/**
	 * Returns the created_date of this buy sell products.
	 *
	 * @return the created_date of this buy sell products
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this buy sell products.
	 *
	 * @param created_date the created_date of this buy sell products
	 */
	public void setCreated_date(Date created_date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BuySellProducts buySellProducts);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BuySellProducts> toCacheModel();

	@Override
	public BuySellProducts toEscapedModel();

	@Override
	public BuySellProducts toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}