/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.book.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the bookusers service. Represents a row in the &quot;chola_bookusers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.book.model.impl.bookusersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.book.model.impl.bookusersImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see bookusers
 * @see com.chola.book.model.impl.bookusersImpl
 * @see com.chola.book.model.impl.bookusersModelImpl
 * @generated
 */
@ProviderType
public interface bookusersModel extends BaseModel<bookusers> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bookusers model instance should use the {@link bookusers} interface instead.
	 */

	/**
	 * Returns the primary key of this bookusers.
	 *
	 * @return the primary key of this bookusers
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bookusers.
	 *
	 * @param primaryKey the primary key of this bookusers
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this bookusers.
	 *
	 * @return the ID of this bookusers
	 */
	public long getId();

	/**
	 * Sets the ID of this bookusers.
	 *
	 * @param id the ID of this bookusers
	 */
	public void setId(long id);

	/**
	 * Returns the user_id of this bookusers.
	 *
	 * @return the user_id of this bookusers
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this bookusers.
	 *
	 * @param user_id the user_id of this bookusers
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the book_id of this bookusers.
	 *
	 * @return the book_id of this bookusers
	 */
	public long getBook_id();

	/**
	 * Sets the book_id of this bookusers.
	 *
	 * @param book_id the book_id of this bookusers
	 */
	public void setBook_id(long book_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.chola.book.model.bookusers bookusers);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.book.model.bookusers> toCacheModel();

	@Override
	public com.chola.book.model.bookusers toEscapedModel();

	@Override
	public com.chola.book.model.bookusers toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}