/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.successstories.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.chola.successstories.model.ssusers;
import com.chola.successstories.model.ssusersModel;
import com.chola.successstories.model.ssusersSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ssusers service. Represents a row in the &quot;chola_ssusers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ssusersModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ssusersImpl}.
 * </p>
 *
 * @author cloverliferay01
 * @see ssusersImpl
 * @see ssusers
 * @see ssusersModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ssusersModelImpl extends BaseModelImpl<ssusers>
	implements ssusersModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ssusers model instance should use the {@link ssusers} interface instead.
	 */
	public static final String TABLE_NAME = "chola_ssusers";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "user_id", Types.BIGINT },
			{ "ssdetails_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("user_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ssdetails_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table chola_ssusers (id_ LONG not null primary key,user_id LONG,ssdetails_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table chola_ssusers";
	public static final String ORDER_BY_JPQL = " ORDER BY ssusers.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY chola_ssusers.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.chola.successstories.model.ssusers"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.chola.successstories.model.ssusers"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.chola.successstories.model.ssusers"),
			true);
	public static final long SSDETAILS_ID_COLUMN_BITMASK = 1L;
	public static final long USER_ID_COLUMN_BITMASK = 2L;
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ssusers toModel(ssusersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ssusers model = new ssusersImpl();

		model.setId(soapModel.getId());
		model.setUser_id(soapModel.getUser_id());
		model.setSsdetails_id(soapModel.getSsdetails_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ssusers> toModels(ssusersSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ssusers> models = new ArrayList<ssusers>(soapModels.length);

		for (ssusersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.chola.successstories.model.ssusers"));

	public ssusersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ssusers.class;
	}

	@Override
	public String getModelClassName() {
		return ssusers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("user_id", getUser_id());
		attributes.put("ssdetails_id", getSsdetails_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long user_id = (Long)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		Long ssdetails_id = (Long)attributes.get("ssdetails_id");

		if (ssdetails_id != null) {
			setSsdetails_id(ssdetails_id);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getUser_id() {
		return _user_id;
	}

	@Override
	public void setUser_id(long user_id) {
		_columnBitmask |= USER_ID_COLUMN_BITMASK;

		if (!_setOriginalUser_id) {
			_setOriginalUser_id = true;

			_originalUser_id = _user_id;
		}

		_user_id = user_id;
	}

	public long getOriginalUser_id() {
		return _originalUser_id;
	}

	@JSON
	@Override
	public long getSsdetails_id() {
		return _ssdetails_id;
	}

	@Override
	public void setSsdetails_id(long ssdetails_id) {
		_columnBitmask |= SSDETAILS_ID_COLUMN_BITMASK;

		if (!_setOriginalSsdetails_id) {
			_setOriginalSsdetails_id = true;

			_originalSsdetails_id = _ssdetails_id;
		}

		_ssdetails_id = ssdetails_id;
	}

	public long getOriginalSsdetails_id() {
		return _originalSsdetails_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ssusers.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ssusers toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ssusers)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ssusersImpl ssusersImpl = new ssusersImpl();

		ssusersImpl.setId(getId());
		ssusersImpl.setUser_id(getUser_id());
		ssusersImpl.setSsdetails_id(getSsdetails_id());

		ssusersImpl.resetOriginalValues();

		return ssusersImpl;
	}

	@Override
	public int compareTo(ssusers ssusers) {
		long primaryKey = ssusers.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ssusers)) {
			return false;
		}

		ssusers ssusers = (ssusers)obj;

		long primaryKey = ssusers.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ssusersModelImpl ssusersModelImpl = this;

		ssusersModelImpl._originalUser_id = ssusersModelImpl._user_id;

		ssusersModelImpl._setOriginalUser_id = false;

		ssusersModelImpl._originalSsdetails_id = ssusersModelImpl._ssdetails_id;

		ssusersModelImpl._setOriginalSsdetails_id = false;

		ssusersModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ssusers> toCacheModel() {
		ssusersCacheModel ssusersCacheModel = new ssusersCacheModel();

		ssusersCacheModel.id = getId();

		ssusersCacheModel.user_id = getUser_id();

		ssusersCacheModel.ssdetails_id = getSsdetails_id();

		return ssusersCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", ssdetails_id=");
		sb.append(getSsdetails_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.chola.successstories.model.ssusers");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ssdetails_id</column-name><column-value><![CDATA[");
		sb.append(getSsdetails_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ssusers.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ssusers.class
		};
	private long _id;
	private long _user_id;
	private long _originalUser_id;
	private boolean _setOriginalUser_id;
	private long _ssdetails_id;
	private long _originalSsdetails_id;
	private boolean _setOriginalSsdetails_id;
	private long _columnBitmask;
	private ssusers _escapedModel;
}