/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.mdspeak.service.base;

import aQute.bnd.annotation.ProviderType;

import com.chola.mdspeak.model.MdSpeaks;
import com.chola.mdspeak.service.MdSpeaksLocalService;
import com.chola.mdspeak.service.persistence.MdSpeaksFinder;
import com.chola.mdspeak.service.persistence.MdSpeaksPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the md speaks local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.chola.mdspeak.service.impl.MdSpeaksLocalServiceImpl}.
 * </p>
 *
 * @author adms.java1
 * @see com.chola.mdspeak.service.impl.MdSpeaksLocalServiceImpl
 * @see com.chola.mdspeak.service.MdSpeaksLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class MdSpeaksLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements MdSpeaksLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.chola.mdspeak.service.MdSpeaksLocalServiceUtil} to access the md speaks local service.
	 */

	/**
	 * Adds the md speaks to the database. Also notifies the appropriate model listeners.
	 *
	 * @param mdSpeaks the md speaks
	 * @return the md speaks that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MdSpeaks addMdSpeaks(MdSpeaks mdSpeaks) {
		mdSpeaks.setNew(true);

		return mdSpeaksPersistence.update(mdSpeaks);
	}

	/**
	 * Creates a new md speaks with the primary key. Does not add the md speaks to the database.
	 *
	 * @param Id the primary key for the new md speaks
	 * @return the new md speaks
	 */
	@Override
	public MdSpeaks createMdSpeaks(long Id) {
		return mdSpeaksPersistence.create(Id);
	}

	/**
	 * Deletes the md speaks with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param Id the primary key of the md speaks
	 * @return the md speaks that was removed
	 * @throws PortalException if a md speaks with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MdSpeaks deleteMdSpeaks(long Id) throws PortalException {
		return mdSpeaksPersistence.remove(Id);
	}

	/**
	 * Deletes the md speaks from the database. Also notifies the appropriate model listeners.
	 *
	 * @param mdSpeaks the md speaks
	 * @return the md speaks that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MdSpeaks deleteMdSpeaks(MdSpeaks mdSpeaks) {
		return mdSpeaksPersistence.remove(mdSpeaks);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MdSpeaks.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return mdSpeaksPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.chola.mdspeak.model.impl.MdSpeaksModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return mdSpeaksPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.chola.mdspeak.model.impl.MdSpeaksModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return mdSpeaksPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return mdSpeaksPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return mdSpeaksPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MdSpeaks fetchMdSpeaks(long Id) {
		return mdSpeaksPersistence.fetchByPrimaryKey(Id);
	}

	/**
	 * Returns the md speaks with the primary key.
	 *
	 * @param Id the primary key of the md speaks
	 * @return the md speaks
	 * @throws PortalException if a md speaks with the primary key could not be found
	 */
	@Override
	public MdSpeaks getMdSpeaks(long Id) throws PortalException {
		return mdSpeaksPersistence.findByPrimaryKey(Id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(mdSpeaksLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MdSpeaks.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("Id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(mdSpeaksLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MdSpeaks.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("Id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(mdSpeaksLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MdSpeaks.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("Id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return mdSpeaksLocalService.deleteMdSpeaks((MdSpeaks)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return mdSpeaksPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the md speakses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.chola.mdspeak.model.impl.MdSpeaksModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of md speakses
	 * @param end the upper bound of the range of md speakses (not inclusive)
	 * @return the range of md speakses
	 */
	@Override
	public List<MdSpeaks> getMdSpeakses(int start, int end) {
		return mdSpeaksPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of md speakses.
	 *
	 * @return the number of md speakses
	 */
	@Override
	public int getMdSpeaksesCount() {
		return mdSpeaksPersistence.countAll();
	}

	/**
	 * Updates the md speaks in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param mdSpeaks the md speaks
	 * @return the md speaks that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MdSpeaks updateMdSpeaks(MdSpeaks mdSpeaks) {
		return mdSpeaksPersistence.update(mdSpeaks);
	}

	/**
	 * Returns the md speaks local service.
	 *
	 * @return the md speaks local service
	 */
	public MdSpeaksLocalService getMdSpeaksLocalService() {
		return mdSpeaksLocalService;
	}

	/**
	 * Sets the md speaks local service.
	 *
	 * @param mdSpeaksLocalService the md speaks local service
	 */
	public void setMdSpeaksLocalService(
		MdSpeaksLocalService mdSpeaksLocalService) {
		this.mdSpeaksLocalService = mdSpeaksLocalService;
	}

	/**
	 * Returns the md speaks persistence.
	 *
	 * @return the md speaks persistence
	 */
	public MdSpeaksPersistence getMdSpeaksPersistence() {
		return mdSpeaksPersistence;
	}

	/**
	 * Sets the md speaks persistence.
	 *
	 * @param mdSpeaksPersistence the md speaks persistence
	 */
	public void setMdSpeaksPersistence(MdSpeaksPersistence mdSpeaksPersistence) {
		this.mdSpeaksPersistence = mdSpeaksPersistence;
	}

	/**
	 * Returns the md speaks finder.
	 *
	 * @return the md speaks finder
	 */
	public MdSpeaksFinder getMdSpeaksFinder() {
		return mdSpeaksFinder;
	}

	/**
	 * Sets the md speaks finder.
	 *
	 * @param mdSpeaksFinder the md speaks finder
	 */
	public void setMdSpeaksFinder(MdSpeaksFinder mdSpeaksFinder) {
		this.mdSpeaksFinder = mdSpeaksFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.chola.mdspeak.model.MdSpeaks",
			mdSpeaksLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.chola.mdspeak.model.MdSpeaks");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MdSpeaksLocalService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return MdSpeaks.class;
	}

	protected String getModelClassName() {
		return MdSpeaks.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = mdSpeaksPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MdSpeaksLocalService.class)
	protected MdSpeaksLocalService mdSpeaksLocalService;
	@BeanReference(type = MdSpeaksPersistence.class)
	protected MdSpeaksPersistence mdSpeaksPersistence;
	@BeanReference(type = MdSpeaksFinder.class)
	protected MdSpeaksFinder mdSpeaksFinder;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private MdSpeaksLocalServiceClpInvoker _clpInvoker = new MdSpeaksLocalServiceClpInvoker();
}