/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.contest.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CholaContest service. Represents a row in the &quot;chola_CholaContest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.contest.model.impl.CholaContestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.contest.model.impl.CholaContestImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see CholaContest
 * @see com.contest.model.impl.CholaContestImpl
 * @see com.contest.model.impl.CholaContestModelImpl
 * @generated
 */
@ProviderType
public interface CholaContestModel extends BaseModel<CholaContest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chola contest model instance should use the {@link CholaContest} interface instead.
	 */

	/**
	 * Returns the primary key of this chola contest.
	 *
	 * @return the primary key of this chola contest
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chola contest.
	 *
	 * @param primaryKey the primary key of this chola contest
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chola contest.
	 *
	 * @return the ID of this chola contest
	 */
	public long getId();

	/**
	 * Sets the ID of this chola contest.
	 *
	 * @param Id the ID of this chola contest
	 */
	public void setId(long Id);

	/**
	 * Returns the content_id of this chola contest.
	 *
	 * @return the content_id of this chola contest
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this chola contest.
	 *
	 * @param content_id the content_id of this chola contest
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the content of this chola contest.
	 *
	 * @return the content of this chola contest
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this chola contest.
	 *
	 * @param content the content of this chola contest
	 */
	public void setContent(String content);

	/**
	 * Returns the startdate of this chola contest.
	 *
	 * @return the startdate of this chola contest
	 */
	public Date getStartdate();

	/**
	 * Sets the startdate of this chola contest.
	 *
	 * @param startdate the startdate of this chola contest
	 */
	public void setStartdate(Date startdate);

	/**
	 * Returns the enddate of this chola contest.
	 *
	 * @return the enddate of this chola contest
	 */
	public Date getEnddate();

	/**
	 * Sets the enddate of this chola contest.
	 *
	 * @param enddate the enddate of this chola contest
	 */
	public void setEnddate(Date enddate);

	/**
	 * Returns the feedback of this chola contest.
	 *
	 * @return the feedback of this chola contest
	 */
	@AutoEscape
	public String getFeedback();

	/**
	 * Sets the feedback of this chola contest.
	 *
	 * @param feedback the feedback of this chola contest
	 */
	public void setFeedback(String feedback);

	/**
	 * Returns the create date of this chola contest.
	 *
	 * @return the create date of this chola contest
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this chola contest.
	 *
	 * @param createDate the create date of this chola contest
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the contest_code of this chola contest.
	 *
	 * @return the contest_code of this chola contest
	 */
	public int getContest_code();

	/**
	 * Sets the contest_code of this chola contest.
	 *
	 * @param contest_code the contest_code of this chola contest
	 */
	public void setContest_code(int contest_code);

	/**
	 * Returns the contest_val of this chola contest.
	 *
	 * @return the contest_val of this chola contest
	 */
	public int getContest_val();

	/**
	 * Sets the contest_val of this chola contest.
	 *
	 * @param contest_val the contest_val of this chola contest
	 */
	public void setContest_val(int contest_val);

	/**
	 * Returns the contest_desc of this chola contest.
	 *
	 * @return the contest_desc of this chola contest
	 */
	@AutoEscape
	public String getContest_desc();

	/**
	 * Sets the contest_desc of this chola contest.
	 *
	 * @param contest_desc the contest_desc of this chola contest
	 */
	public void setContest_desc(String contest_desc);

	/**
	 * Returns the contest_doc of this chola contest.
	 *
	 * @return the contest_doc of this chola contest
	 */
	@AutoEscape
	public String getContest_doc();

	/**
	 * Sets the contest_doc of this chola contest.
	 *
	 * @param contest_doc the contest_doc of this chola contest
	 */
	public void setContest_doc(String contest_doc);

	/**
	 * Returns the contest_path of this chola contest.
	 *
	 * @return the contest_path of this chola contest
	 */
	@AutoEscape
	public String getContest_path();

	/**
	 * Sets the contest_path of this chola contest.
	 *
	 * @param contest_path the contest_path of this chola contest
	 */
	public void setContest_path(String contest_path);

	/**
	 * Returns the contest_title of this chola contest.
	 *
	 * @return the contest_title of this chola contest
	 */
	@AutoEscape
	public String getContest_title();

	/**
	 * Sets the contest_title of this chola contest.
	 *
	 * @param contest_title the contest_title of this chola contest
	 */
	public void setContest_title(String contest_title);

	/**
	 * Returns the user_id of this chola contest.
	 *
	 * @return the user_id of this chola contest
	 */
	@AutoEscape
	public String getUser_id();

	/**
	 * Sets the user_id of this chola contest.
	 *
	 * @param user_id the user_id of this chola contest
	 */
	public void setUser_id(String user_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CholaContest cholaContest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CholaContest> toCacheModel();

	@Override
	public CholaContest toEscapedModel();

	@Override
	public CholaContest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}