/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.contest.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ContestUserDetails service. Represents a row in the &quot;chola_ContestUserDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.contest.model.impl.ContestUserDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.contest.model.impl.ContestUserDetailsImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see ContestUserDetails
 * @see com.contest.model.impl.ContestUserDetailsImpl
 * @see com.contest.model.impl.ContestUserDetailsModelImpl
 * @generated
 */
@ProviderType
public interface ContestUserDetailsModel extends BaseModel<ContestUserDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contest user details model instance should use the {@link ContestUserDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this contest user details.
	 *
	 * @return the primary key of this contest user details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contest user details.
	 *
	 * @param primaryKey the primary key of this contest user details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this contest user details.
	 *
	 * @return the ID of this contest user details
	 */
	public long getId();

	/**
	 * Sets the ID of this contest user details.
	 *
	 * @param id the ID of this contest user details
	 */
	public void setId(long id);

	/**
	 * Returns the user_id of this contest user details.
	 *
	 * @return the user_id of this contest user details
	 */
	@AutoEscape
	public String getUser_id();

	/**
	 * Sets the user_id of this contest user details.
	 *
	 * @param user_id the user_id of this contest user details
	 */
	public void setUser_id(String user_id);

	/**
	 * Returns the contestreference_id of this contest user details.
	 *
	 * @return the contestreference_id of this contest user details
	 */
	public long getContestreference_id();

	/**
	 * Sets the contestreference_id of this contest user details.
	 *
	 * @param contestreference_id the contestreference_id of this contest user details
	 */
	public void setContestreference_id(long contestreference_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ContestUserDetails contestUserDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ContestUserDetails> toCacheModel();

	@Override
	public ContestUserDetails toEscapedModel();

	@Override
	public ContestUserDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}