/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.contest.service.base;

import com.contest.model.ContestUserDetails;

import com.contest.service.ContestUserDetailsService;
import com.contest.service.persistence.CholaContestFinder;
import com.contest.service.persistence.CholaContestPersistence;
import com.contest.service.persistence.ContestUserDetailsPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the contest user details remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.contest.service.impl.ContestUserDetailsServiceImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see com.contest.service.impl.ContestUserDetailsServiceImpl
 * @see com.contest.service.ContestUserDetailsServiceUtil
 * @generated
 */
public abstract class ContestUserDetailsServiceBaseImpl extends BaseServiceImpl
	implements ContestUserDetailsService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.contest.service.ContestUserDetailsServiceUtil} to access the contest user details remote service.
	 */

	/**
	 * Returns the chola contest local service.
	 *
	 * @return the chola contest local service
	 */
	public com.contest.service.CholaContestLocalService getCholaContestLocalService() {
		return cholaContestLocalService;
	}

	/**
	 * Sets the chola contest local service.
	 *
	 * @param cholaContestLocalService the chola contest local service
	 */
	public void setCholaContestLocalService(
		com.contest.service.CholaContestLocalService cholaContestLocalService) {
		this.cholaContestLocalService = cholaContestLocalService;
	}

	/**
	 * Returns the chola contest remote service.
	 *
	 * @return the chola contest remote service
	 */
	public com.contest.service.CholaContestService getCholaContestService() {
		return cholaContestService;
	}

	/**
	 * Sets the chola contest remote service.
	 *
	 * @param cholaContestService the chola contest remote service
	 */
	public void setCholaContestService(
		com.contest.service.CholaContestService cholaContestService) {
		this.cholaContestService = cholaContestService;
	}

	/**
	 * Returns the chola contest persistence.
	 *
	 * @return the chola contest persistence
	 */
	public CholaContestPersistence getCholaContestPersistence() {
		return cholaContestPersistence;
	}

	/**
	 * Sets the chola contest persistence.
	 *
	 * @param cholaContestPersistence the chola contest persistence
	 */
	public void setCholaContestPersistence(
		CholaContestPersistence cholaContestPersistence) {
		this.cholaContestPersistence = cholaContestPersistence;
	}

	/**
	 * Returns the chola contest finder.
	 *
	 * @return the chola contest finder
	 */
	public CholaContestFinder getCholaContestFinder() {
		return cholaContestFinder;
	}

	/**
	 * Sets the chola contest finder.
	 *
	 * @param cholaContestFinder the chola contest finder
	 */
	public void setCholaContestFinder(CholaContestFinder cholaContestFinder) {
		this.cholaContestFinder = cholaContestFinder;
	}

	/**
	 * Returns the contest user details local service.
	 *
	 * @return the contest user details local service
	 */
	public com.contest.service.ContestUserDetailsLocalService getContestUserDetailsLocalService() {
		return contestUserDetailsLocalService;
	}

	/**
	 * Sets the contest user details local service.
	 *
	 * @param contestUserDetailsLocalService the contest user details local service
	 */
	public void setContestUserDetailsLocalService(
		com.contest.service.ContestUserDetailsLocalService contestUserDetailsLocalService) {
		this.contestUserDetailsLocalService = contestUserDetailsLocalService;
	}

	/**
	 * Returns the contest user details remote service.
	 *
	 * @return the contest user details remote service
	 */
	public ContestUserDetailsService getContestUserDetailsService() {
		return contestUserDetailsService;
	}

	/**
	 * Sets the contest user details remote service.
	 *
	 * @param contestUserDetailsService the contest user details remote service
	 */
	public void setContestUserDetailsService(
		ContestUserDetailsService contestUserDetailsService) {
		this.contestUserDetailsService = contestUserDetailsService;
	}

	/**
	 * Returns the contest user details persistence.
	 *
	 * @return the contest user details persistence
	 */
	public ContestUserDetailsPersistence getContestUserDetailsPersistence() {
		return contestUserDetailsPersistence;
	}

	/**
	 * Sets the contest user details persistence.
	 *
	 * @param contestUserDetailsPersistence the contest user details persistence
	 */
	public void setContestUserDetailsPersistence(
		ContestUserDetailsPersistence contestUserDetailsPersistence) {
		this.contestUserDetailsPersistence = contestUserDetailsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ContestUserDetailsService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ContestUserDetails.class;
	}

	protected String getModelClassName() {
		return ContestUserDetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = contestUserDetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.contest.service.CholaContestLocalService.class)
	protected com.contest.service.CholaContestLocalService cholaContestLocalService;
	@BeanReference(type = com.contest.service.CholaContestService.class)
	protected com.contest.service.CholaContestService cholaContestService;
	@BeanReference(type = CholaContestPersistence.class)
	protected CholaContestPersistence cholaContestPersistence;
	@BeanReference(type = CholaContestFinder.class)
	protected CholaContestFinder cholaContestFinder;
	@BeanReference(type = com.contest.service.ContestUserDetailsLocalService.class)
	protected com.contest.service.ContestUserDetailsLocalService contestUserDetailsLocalService;
	@BeanReference(type = ContestUserDetailsService.class)
	protected ContestUserDetailsService contestUserDetailsService;
	@BeanReference(type = ContestUserDetailsPersistence.class)
	protected ContestUserDetailsPersistence contestUserDetailsPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private ContestUserDetailsServiceClpInvoker _clpInvoker = new ContestUserDetailsServiceClpInvoker();
}