/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.bsop.service.base;

import com.chola.bsop.model.bsopdetails;
import com.chola.bsop.service.bsopdetailsService;
import com.chola.bsop.service.persistence.bsopdetailsPersistence;
import com.chola.bsop.service.persistence.bsoppathPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the bsopdetails remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.chola.bsop.service.impl.bsopdetailsServiceImpl}.
 * </p>
 *
 * @author cloverliferay01
 * @see com.chola.bsop.service.impl.bsopdetailsServiceImpl
 * @see com.chola.bsop.service.bsopdetailsServiceUtil
 * @generated
 */
public abstract class bsopdetailsServiceBaseImpl extends BaseServiceImpl
	implements bsopdetailsService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.chola.bsop.service.bsopdetailsServiceUtil} to access the bsopdetails remote service.
	 */

	/**
	 * Returns the bsopdetails local service.
	 *
	 * @return the bsopdetails local service
	 */
	public com.chola.bsop.service.bsopdetailsLocalService getbsopdetailsLocalService() {
		return bsopdetailsLocalService;
	}

	/**
	 * Sets the bsopdetails local service.
	 *
	 * @param bsopdetailsLocalService the bsopdetails local service
	 */
	public void setbsopdetailsLocalService(
		com.chola.bsop.service.bsopdetailsLocalService bsopdetailsLocalService) {
		this.bsopdetailsLocalService = bsopdetailsLocalService;
	}

	/**
	 * Returns the bsopdetails remote service.
	 *
	 * @return the bsopdetails remote service
	 */
	public bsopdetailsService getbsopdetailsService() {
		return bsopdetailsService;
	}

	/**
	 * Sets the bsopdetails remote service.
	 *
	 * @param bsopdetailsService the bsopdetails remote service
	 */
	public void setbsopdetailsService(bsopdetailsService bsopdetailsService) {
		this.bsopdetailsService = bsopdetailsService;
	}

	/**
	 * Returns the bsopdetails persistence.
	 *
	 * @return the bsopdetails persistence
	 */
	public bsopdetailsPersistence getbsopdetailsPersistence() {
		return bsopdetailsPersistence;
	}

	/**
	 * Sets the bsopdetails persistence.
	 *
	 * @param bsopdetailsPersistence the bsopdetails persistence
	 */
	public void setbsopdetailsPersistence(
		bsopdetailsPersistence bsopdetailsPersistence) {
		this.bsopdetailsPersistence = bsopdetailsPersistence;
	}

	/**
	 * Returns the bsoppath local service.
	 *
	 * @return the bsoppath local service
	 */
	public com.chola.bsop.service.bsoppathLocalService getbsoppathLocalService() {
		return bsoppathLocalService;
	}

	/**
	 * Sets the bsoppath local service.
	 *
	 * @param bsoppathLocalService the bsoppath local service
	 */
	public void setbsoppathLocalService(
		com.chola.bsop.service.bsoppathLocalService bsoppathLocalService) {
		this.bsoppathLocalService = bsoppathLocalService;
	}

	/**
	 * Returns the bsoppath remote service.
	 *
	 * @return the bsoppath remote service
	 */
	public com.chola.bsop.service.bsoppathService getbsoppathService() {
		return bsoppathService;
	}

	/**
	 * Sets the bsoppath remote service.
	 *
	 * @param bsoppathService the bsoppath remote service
	 */
	public void setbsoppathService(
		com.chola.bsop.service.bsoppathService bsoppathService) {
		this.bsoppathService = bsoppathService;
	}

	/**
	 * Returns the bsoppath persistence.
	 *
	 * @return the bsoppath persistence
	 */
	public bsoppathPersistence getbsoppathPersistence() {
		return bsoppathPersistence;
	}

	/**
	 * Sets the bsoppath persistence.
	 *
	 * @param bsoppathPersistence the bsoppath persistence
	 */
	public void setbsoppathPersistence(bsoppathPersistence bsoppathPersistence) {
		this.bsoppathPersistence = bsoppathPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return bsopdetailsService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return bsopdetails.class;
	}

	protected String getModelClassName() {
		return bsopdetails.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = bsopdetailsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.chola.bsop.service.bsopdetailsLocalService.class)
	protected com.chola.bsop.service.bsopdetailsLocalService bsopdetailsLocalService;
	@BeanReference(type = bsopdetailsService.class)
	protected bsopdetailsService bsopdetailsService;
	@BeanReference(type = bsopdetailsPersistence.class)
	protected bsopdetailsPersistence bsopdetailsPersistence;
	@BeanReference(type = com.chola.bsop.service.bsoppathLocalService.class)
	protected com.chola.bsop.service.bsoppathLocalService bsoppathLocalService;
	@BeanReference(type = com.chola.bsop.service.bsoppathService.class)
	protected com.chola.bsop.service.bsoppathService bsoppathService;
	@BeanReference(type = bsoppathPersistence.class)
	protected bsoppathPersistence bsoppathPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private bsopdetailsServiceClpInvoker _clpInvoker = new bsopdetailsServiceClpInvoker();
}