/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.successstories.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ssdetails service. Represents a row in the &quot;chola_ssdetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.successstories.model.impl.ssdetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.successstories.model.impl.ssdetailsImpl}.
 * </p>
 *
 * @author cloverliferay01
 * @see ssdetails
 * @see com.chola.successstories.model.impl.ssdetailsImpl
 * @see com.chola.successstories.model.impl.ssdetailsModelImpl
 * @generated
 */
@ProviderType
public interface ssdetailsModel extends BaseModel<ssdetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ssdetails model instance should use the {@link ssdetails} interface instead.
	 */

	/**
	 * Returns the primary key of this ssdetails.
	 *
	 * @return the primary key of this ssdetails
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ssdetails.
	 *
	 * @param primaryKey the primary key of this ssdetails
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this ssdetails.
	 *
	 * @return the ID of this ssdetails
	 */
	public long getId();

	/**
	 * Sets the ID of this ssdetails.
	 *
	 * @param id the ID of this ssdetails
	 */
	public void setId(long id);

	/**
	 * Returns the content_id of this ssdetails.
	 *
	 * @return the content_id of this ssdetails
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this ssdetails.
	 *
	 * @param content_id the content_id of this ssdetails
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the sstitle of this ssdetails.
	 *
	 * @return the sstitle of this ssdetails
	 */
	@AutoEscape
	public String getSstitle();

	/**
	 * Sets the sstitle of this ssdetails.
	 *
	 * @param sstitle the sstitle of this ssdetails
	 */
	public void setSstitle(String sstitle);

	/**
	 * Returns the ssdesc of this ssdetails.
	 *
	 * @return the ssdesc of this ssdetails
	 */
	@AutoEscape
	public String getSsdesc();

	/**
	 * Sets the ssdesc of this ssdetails.
	 *
	 * @param ssdesc the ssdesc of this ssdetails
	 */
	public void setSsdesc(String ssdesc);

	/**
	 * Returns the created date of this ssdetails.
	 *
	 * @return the created date of this ssdetails
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ssdetails.
	 *
	 * @param createdDate the created date of this ssdetails
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this ssdetails.
	 *
	 * @return the created by of this ssdetails
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this ssdetails.
	 *
	 * @param createdBy the created by of this ssdetails
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this ssdetails.
	 *
	 * @return the modified date of this ssdetails
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ssdetails.
	 *
	 * @param modifiedDate the modified date of this ssdetails
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this ssdetails.
	 *
	 * @return the modified by of this ssdetails
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this ssdetails.
	 *
	 * @param modifiedBy the modified by of this ssdetails
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the flag of this ssdetails.
	 *
	 * @return the flag of this ssdetails
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this ssdetails.
	 *
	 * @param flag the flag of this ssdetails
	 */
	public void setFlag(String flag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.chola.successstories.model.ssdetails ssdetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.successstories.model.ssdetails> toCacheModel();

	@Override
	public com.chola.successstories.model.ssdetails toEscapedModel();

	@Override
	public com.chola.successstories.model.ssdetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}