/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.successstories.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the sspath service. Represents a row in the &quot;chola_sspath&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.successstories.model.impl.sspathModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.successstories.model.impl.sspathImpl}.
 * </p>
 *
 * @author cloverliferay01
 * @see sspath
 * @see com.chola.successstories.model.impl.sspathImpl
 * @see com.chola.successstories.model.impl.sspathModelImpl
 * @generated
 */
@ProviderType
public interface sspathModel extends BaseModel<sspath> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sspath model instance should use the {@link sspath} interface instead.
	 */

	/**
	 * Returns the primary key of this sspath.
	 *
	 * @return the primary key of this sspath
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sspath.
	 *
	 * @param primaryKey the primary key of this sspath
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this sspath.
	 *
	 * @return the ID of this sspath
	 */
	public long getId();

	/**
	 * Sets the ID of this sspath.
	 *
	 * @param id the ID of this sspath
	 */
	public void setId(long id);

	/**
	 * Returns the ssfiledoc of this sspath.
	 *
	 * @return the ssfiledoc of this sspath
	 */
	@AutoEscape
	public String getSsfiledoc();

	/**
	 * Sets the ssfiledoc of this sspath.
	 *
	 * @param ssfiledoc the ssfiledoc of this sspath
	 */
	public void setSsfiledoc(String ssfiledoc);

	/**
	 * Returns the ssfilepath of this sspath.
	 *
	 * @return the ssfilepath of this sspath
	 */
	@AutoEscape
	public String getSsfilepath();

	/**
	 * Sets the ssfilepath of this sspath.
	 *
	 * @param ssfilepath the ssfilepath of this sspath
	 */
	public void setSsfilepath(String ssfilepath);

	/**
	 * Returns the created date of this sspath.
	 *
	 * @return the created date of this sspath
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this sspath.
	 *
	 * @param createdDate the created date of this sspath
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this sspath.
	 *
	 * @return the created by of this sspath
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this sspath.
	 *
	 * @param createdBy the created by of this sspath
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the flag of this sspath.
	 *
	 * @return the flag of this sspath
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this sspath.
	 *
	 * @param flag the flag of this sspath
	 */
	public void setFlag(String flag);

	/**
	 * Returns the ssdetails_id of this sspath.
	 *
	 * @return the ssdetails_id of this sspath
	 */
	public long getSsdetails_id();

	/**
	 * Sets the ssdetails_id of this sspath.
	 *
	 * @param ssdetails_id the ssdetails_id of this sspath
	 */
	public void setSsdetails_id(long ssdetails_id);

	/**
	 * Returns the content_id of this sspath.
	 *
	 * @return the content_id of this sspath
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this sspath.
	 *
	 * @param content_id the content_id of this sspath
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the ssfilename of this sspath.
	 *
	 * @return the ssfilename of this sspath
	 */
	@AutoEscape
	public String getSsfilename();

	/**
	 * Sets the ssfilename of this sspath.
	 *
	 * @param ssfilename the ssfilename of this sspath
	 */
	public void setSsfilename(String ssfilename);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.chola.successstories.model.sspath sspath);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.successstories.model.sspath> toCacheModel();

	@Override
	public com.chola.successstories.model.sspath toEscapedModel();

	@Override
	public com.chola.successstories.model.sspath toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}