/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.contest.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.contest.model.ContestUserDetails;
import com.contest.model.ContestUserDetailsModel;
import com.contest.model.ContestUserDetailsSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ContestUserDetails service. Represents a row in the &quot;chola_ContestUserDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ContestUserDetailsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContestUserDetailsImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see ContestUserDetailsImpl
 * @see ContestUserDetails
 * @see ContestUserDetailsModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ContestUserDetailsModelImpl extends BaseModelImpl<ContestUserDetails>
	implements ContestUserDetailsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contest user details model instance should use the {@link ContestUserDetails} interface instead.
	 */
	public static final String TABLE_NAME = "chola_ContestUserDetails";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "user_id", Types.VARCHAR },
			{ "contestreference_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("user_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contestreference_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table chola_ContestUserDetails (id_ LONG not null primary key,user_id VARCHAR(75) null,contestreference_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table chola_ContestUserDetails";
	public static final String ORDER_BY_JPQL = " ORDER BY contestUserDetails.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY chola_ContestUserDetails.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.contest.model.ContestUserDetails"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.contest.model.ContestUserDetails"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.contest.model.ContestUserDetails"),
			true);
	public static final long CONTESTREFERENCE_ID_COLUMN_BITMASK = 1L;
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContestUserDetails toModel(ContestUserDetailsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ContestUserDetails model = new ContestUserDetailsImpl();

		model.setId(soapModel.getId());
		model.setUser_id(soapModel.getUser_id());
		model.setContestreference_id(soapModel.getContestreference_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContestUserDetails> toModels(
		ContestUserDetailsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ContestUserDetails> models = new ArrayList<ContestUserDetails>(soapModels.length);

		for (ContestUserDetailsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.contest.model.ContestUserDetails"));

	public ContestUserDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContestUserDetails.class;
	}

	@Override
	public String getModelClassName() {
		return ContestUserDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("user_id", getUser_id());
		attributes.put("contestreference_id", getContestreference_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String user_id = (String)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		Long contestreference_id = (Long)attributes.get("contestreference_id");

		if (contestreference_id != null) {
			setContestreference_id(contestreference_id);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getUser_id() {
		if (_user_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _user_id;
		}
	}

	@Override
	public void setUser_id(String user_id) {
		_user_id = user_id;
	}

	@JSON
	@Override
	public long getContestreference_id() {
		return _contestreference_id;
	}

	@Override
	public void setContestreference_id(long contestreference_id) {
		_columnBitmask |= CONTESTREFERENCE_ID_COLUMN_BITMASK;

		if (!_setOriginalContestreference_id) {
			_setOriginalContestreference_id = true;

			_originalContestreference_id = _contestreference_id;
		}

		_contestreference_id = contestreference_id;
	}

	public long getOriginalContestreference_id() {
		return _originalContestreference_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ContestUserDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContestUserDetails toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ContestUserDetails)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContestUserDetailsImpl contestUserDetailsImpl = new ContestUserDetailsImpl();

		contestUserDetailsImpl.setId(getId());
		contestUserDetailsImpl.setUser_id(getUser_id());
		contestUserDetailsImpl.setContestreference_id(getContestreference_id());

		contestUserDetailsImpl.resetOriginalValues();

		return contestUserDetailsImpl;
	}

	@Override
	public int compareTo(ContestUserDetails contestUserDetails) {
		long primaryKey = contestUserDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ContestUserDetails)) {
			return false;
		}

		ContestUserDetails contestUserDetails = (ContestUserDetails)obj;

		long primaryKey = contestUserDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ContestUserDetailsModelImpl contestUserDetailsModelImpl = this;

		contestUserDetailsModelImpl._originalContestreference_id = contestUserDetailsModelImpl._contestreference_id;

		contestUserDetailsModelImpl._setOriginalContestreference_id = false;

		contestUserDetailsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContestUserDetails> toCacheModel() {
		ContestUserDetailsCacheModel contestUserDetailsCacheModel = new ContestUserDetailsCacheModel();

		contestUserDetailsCacheModel.id = getId();

		contestUserDetailsCacheModel.user_id = getUser_id();

		String user_id = contestUserDetailsCacheModel.user_id;

		if ((user_id != null) && (user_id.length() == 0)) {
			contestUserDetailsCacheModel.user_id = null;
		}

		contestUserDetailsCacheModel.contestreference_id = getContestreference_id();

		return contestUserDetailsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", contestreference_id=");
		sb.append(getContestreference_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.contest.model.ContestUserDetails");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contestreference_id</column-name><column-value><![CDATA[");
		sb.append(getContestreference_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ContestUserDetails.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ContestUserDetails.class
		};
	private long _id;
	private String _user_id;
	private long _contestreference_id;
	private long _originalContestreference_id;
	private boolean _setOriginalContestreference_id;
	private long _columnBitmask;
	private ContestUserDetails _escapedModel;
}