/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.calendar.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the corporatecontentuniqueinformation service. Represents a row in the &quot;events_corporatecontentuniqueinformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.calendar.model.impl.corporatecontentuniqueinformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.calendar.model.impl.corporatecontentuniqueinformationImpl}.
 * </p>
 *
 * @author adms.java1
 * @see corporatecontentuniqueinformation
 * @see com.chola.calendar.model.impl.corporatecontentuniqueinformationImpl
 * @see com.chola.calendar.model.impl.corporatecontentuniqueinformationModelImpl
 * @generated
 */
@ProviderType
public interface corporatecontentuniqueinformationModel extends BaseModel<corporatecontentuniqueinformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a corporatecontentuniqueinformation model instance should use the {@link corporatecontentuniqueinformation} interface instead.
	 */

	/**
	 * Returns the primary key of this corporatecontentuniqueinformation.
	 *
	 * @return the primary key of this corporatecontentuniqueinformation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this corporatecontentuniqueinformation.
	 *
	 * @param primaryKey the primary key of this corporatecontentuniqueinformation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this corporatecontentuniqueinformation.
	 *
	 * @return the ID of this corporatecontentuniqueinformation
	 */
	public long getId();

	/**
	 * Sets the ID of this corporatecontentuniqueinformation.
	 *
	 * @param id the ID of this corporatecontentuniqueinformation
	 */
	public void setId(long id);

	/**
	 * Returns the corporatevent_id of this corporatecontentuniqueinformation.
	 *
	 * @return the corporatevent_id of this corporatecontentuniqueinformation
	 */
	public long getCorporatevent_id();

	/**
	 * Sets the corporatevent_id of this corporatecontentuniqueinformation.
	 *
	 * @param corporatevent_id the corporatevent_id of this corporatecontentuniqueinformation
	 */
	public void setCorporatevent_id(long corporatevent_id);

	/**
	 * Returns the content_id of this corporatecontentuniqueinformation.
	 *
	 * @return the content_id of this corporatecontentuniqueinformation
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this corporatecontentuniqueinformation.
	 *
	 * @param content_id the content_id of this corporatecontentuniqueinformation
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the status of this corporatecontentuniqueinformation.
	 *
	 * @return the status of this corporatecontentuniqueinformation
	 */
	public long getStatus();

	/**
	 * Sets the status of this corporatecontentuniqueinformation.
	 *
	 * @param status the status of this corporatecontentuniqueinformation
	 */
	public void setStatus(long status);

	/**
	 * Returns the udflag of this corporatecontentuniqueinformation.
	 *
	 * @return the udflag of this corporatecontentuniqueinformation
	 */
	public long getUdflag();

	/**
	 * Sets the udflag of this corporatecontentuniqueinformation.
	 *
	 * @param udflag the udflag of this corporatecontentuniqueinformation
	 */
	public void setUdflag(long udflag);

	/**
	 * Returns the content_type of this corporatecontentuniqueinformation.
	 *
	 * @return the content_type of this corporatecontentuniqueinformation
	 */
	@AutoEscape
	public String getContent_type();

	/**
	 * Sets the content_type of this corporatecontentuniqueinformation.
	 *
	 * @param content_type the content_type of this corporatecontentuniqueinformation
	 */
	public void setContent_type(String content_type);

	/**
	 * Returns the notification_text of this corporatecontentuniqueinformation.
	 *
	 * @return the notification_text of this corporatecontentuniqueinformation
	 */
	@AutoEscape
	public String getNotification_text();

	/**
	 * Sets the notification_text of this corporatecontentuniqueinformation.
	 *
	 * @param notification_text the notification_text of this corporatecontentuniqueinformation
	 */
	public void setNotification_text(String notification_text);

	/**
	 * Returns the pageurl of this corporatecontentuniqueinformation.
	 *
	 * @return the pageurl of this corporatecontentuniqueinformation
	 */
	@AutoEscape
	public String getPageurl();

	/**
	 * Sets the pageurl of this corporatecontentuniqueinformation.
	 *
	 * @param pageurl the pageurl of this corporatecontentuniqueinformation
	 */
	public void setPageurl(String pageurl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.calendar.model.corporatecontentuniqueinformation corporatecontentuniqueinformation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.calendar.model.corporatecontentuniqueinformation> toCacheModel();

	@Override
	public com.chola.calendar.model.corporatecontentuniqueinformation toEscapedModel();

	@Override
	public com.chola.calendar.model.corporatecontentuniqueinformation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}