/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.ppcontent.service.base;

import aQute.bnd.annotation.ProviderType;

import com.chola.ppcontent.model.personalisedparameterscontentstore;
import com.chola.ppcontent.service.persistence.contentuniqueinformationPersistence;
import com.chola.ppcontent.service.persistence.contentupdateFinder;
import com.chola.ppcontent.service.persistence.contentupdatePersistence;
import com.chola.ppcontent.service.persistence.personalisedparameterscontentstorePersistence;
import com.chola.ppcontent.service.personalisedparameterscontentstoreLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the personalisedparameterscontentstore local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.chola.ppcontent.service.impl.personalisedparameterscontentstoreLocalServiceImpl}.
 * </p>
 *
 * @author cloverliferay01
 * @see com.chola.ppcontent.service.impl.personalisedparameterscontentstoreLocalServiceImpl
 * @see com.chola.ppcontent.service.personalisedparameterscontentstoreLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class personalisedparameterscontentstoreLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements personalisedparameterscontentstoreLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.chola.ppcontent.service.personalisedparameterscontentstoreLocalServiceUtil} to access the personalisedparameterscontentstore local service.
	 */

	/**
	 * Adds the personalisedparameterscontentstore to the database. Also notifies the appropriate model listeners.
	 *
	 * @param personalisedparameterscontentstore the personalisedparameterscontentstore
	 * @return the personalisedparameterscontentstore that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public personalisedparameterscontentstore addpersonalisedparameterscontentstore(
		personalisedparameterscontentstore personalisedparameterscontentstore) {
		personalisedparameterscontentstore.setNew(true);

		return personalisedparameterscontentstorePersistence.update(personalisedparameterscontentstore);
	}

	/**
	 * Creates a new personalisedparameterscontentstore with the primary key. Does not add the personalisedparameterscontentstore to the database.
	 *
	 * @param id the primary key for the new personalisedparameterscontentstore
	 * @return the new personalisedparameterscontentstore
	 */
	@Override
	public personalisedparameterscontentstore createpersonalisedparameterscontentstore(
		long id) {
		return personalisedparameterscontentstorePersistence.create(id);
	}

	/**
	 * Deletes the personalisedparameterscontentstore with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the personalisedparameterscontentstore
	 * @return the personalisedparameterscontentstore that was removed
	 * @throws PortalException if a personalisedparameterscontentstore with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public personalisedparameterscontentstore deletepersonalisedparameterscontentstore(
		long id) throws PortalException {
		return personalisedparameterscontentstorePersistence.remove(id);
	}

	/**
	 * Deletes the personalisedparameterscontentstore from the database. Also notifies the appropriate model listeners.
	 *
	 * @param personalisedparameterscontentstore the personalisedparameterscontentstore
	 * @return the personalisedparameterscontentstore that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public personalisedparameterscontentstore deletepersonalisedparameterscontentstore(
		personalisedparameterscontentstore personalisedparameterscontentstore) {
		return personalisedparameterscontentstorePersistence.remove(personalisedparameterscontentstore);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(personalisedparameterscontentstore.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return personalisedparameterscontentstorePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.chola.ppcontent.model.impl.personalisedparameterscontentstoreModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return personalisedparameterscontentstorePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.chola.ppcontent.model.impl.personalisedparameterscontentstoreModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return personalisedparameterscontentstorePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return personalisedparameterscontentstorePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return personalisedparameterscontentstorePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public personalisedparameterscontentstore fetchpersonalisedparameterscontentstore(
		long id) {
		return personalisedparameterscontentstorePersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the personalisedparameterscontentstore with the primary key.
	 *
	 * @param id the primary key of the personalisedparameterscontentstore
	 * @return the personalisedparameterscontentstore
	 * @throws PortalException if a personalisedparameterscontentstore with the primary key could not be found
	 */
	@Override
	public personalisedparameterscontentstore getpersonalisedparameterscontentstore(
		long id) throws PortalException {
		return personalisedparameterscontentstorePersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(personalisedparameterscontentstoreLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(personalisedparameterscontentstore.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(personalisedparameterscontentstoreLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(personalisedparameterscontentstore.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(personalisedparameterscontentstoreLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(personalisedparameterscontentstore.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return personalisedparameterscontentstoreLocalService.deletepersonalisedparameterscontentstore((personalisedparameterscontentstore)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return personalisedparameterscontentstorePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the personalisedparameterscontentstores.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.chola.ppcontent.model.impl.personalisedparameterscontentstoreModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of personalisedparameterscontentstores
	 * @param end the upper bound of the range of personalisedparameterscontentstores (not inclusive)
	 * @return the range of personalisedparameterscontentstores
	 */
	@Override
	public List<personalisedparameterscontentstore> getpersonalisedparameterscontentstores(
		int start, int end) {
		return personalisedparameterscontentstorePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of personalisedparameterscontentstores.
	 *
	 * @return the number of personalisedparameterscontentstores
	 */
	@Override
	public int getpersonalisedparameterscontentstoresCount() {
		return personalisedparameterscontentstorePersistence.countAll();
	}

	/**
	 * Updates the personalisedparameterscontentstore in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param personalisedparameterscontentstore the personalisedparameterscontentstore
	 * @return the personalisedparameterscontentstore that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public personalisedparameterscontentstore updatepersonalisedparameterscontentstore(
		personalisedparameterscontentstore personalisedparameterscontentstore) {
		return personalisedparameterscontentstorePersistence.update(personalisedparameterscontentstore);
	}

	/**
	 * Returns the contentuniqueinformation local service.
	 *
	 * @return the contentuniqueinformation local service
	 */
	public com.chola.ppcontent.service.contentuniqueinformationLocalService getcontentuniqueinformationLocalService() {
		return contentuniqueinformationLocalService;
	}

	/**
	 * Sets the contentuniqueinformation local service.
	 *
	 * @param contentuniqueinformationLocalService the contentuniqueinformation local service
	 */
	public void setcontentuniqueinformationLocalService(
		com.chola.ppcontent.service.contentuniqueinformationLocalService contentuniqueinformationLocalService) {
		this.contentuniqueinformationLocalService = contentuniqueinformationLocalService;
	}

	/**
	 * Returns the contentuniqueinformation persistence.
	 *
	 * @return the contentuniqueinformation persistence
	 */
	public contentuniqueinformationPersistence getcontentuniqueinformationPersistence() {
		return contentuniqueinformationPersistence;
	}

	/**
	 * Sets the contentuniqueinformation persistence.
	 *
	 * @param contentuniqueinformationPersistence the contentuniqueinformation persistence
	 */
	public void setcontentuniqueinformationPersistence(
		contentuniqueinformationPersistence contentuniqueinformationPersistence) {
		this.contentuniqueinformationPersistence = contentuniqueinformationPersistence;
	}

	/**
	 * Returns the contentupdate local service.
	 *
	 * @return the contentupdate local service
	 */
	public com.chola.ppcontent.service.contentupdateLocalService getcontentupdateLocalService() {
		return contentupdateLocalService;
	}

	/**
	 * Sets the contentupdate local service.
	 *
	 * @param contentupdateLocalService the contentupdate local service
	 */
	public void setcontentupdateLocalService(
		com.chola.ppcontent.service.contentupdateLocalService contentupdateLocalService) {
		this.contentupdateLocalService = contentupdateLocalService;
	}

	/**
	 * Returns the contentupdate persistence.
	 *
	 * @return the contentupdate persistence
	 */
	public contentupdatePersistence getcontentupdatePersistence() {
		return contentupdatePersistence;
	}

	/**
	 * Sets the contentupdate persistence.
	 *
	 * @param contentupdatePersistence the contentupdate persistence
	 */
	public void setcontentupdatePersistence(
		contentupdatePersistence contentupdatePersistence) {
		this.contentupdatePersistence = contentupdatePersistence;
	}

	/**
	 * Returns the contentupdate finder.
	 *
	 * @return the contentupdate finder
	 */
	public contentupdateFinder getcontentupdateFinder() {
		return contentupdateFinder;
	}

	/**
	 * Sets the contentupdate finder.
	 *
	 * @param contentupdateFinder the contentupdate finder
	 */
	public void setcontentupdateFinder(contentupdateFinder contentupdateFinder) {
		this.contentupdateFinder = contentupdateFinder;
	}

	/**
	 * Returns the personalisedparameterscontentstore local service.
	 *
	 * @return the personalisedparameterscontentstore local service
	 */
	public personalisedparameterscontentstoreLocalService getpersonalisedparameterscontentstoreLocalService() {
		return personalisedparameterscontentstoreLocalService;
	}

	/**
	 * Sets the personalisedparameterscontentstore local service.
	 *
	 * @param personalisedparameterscontentstoreLocalService the personalisedparameterscontentstore local service
	 */
	public void setpersonalisedparameterscontentstoreLocalService(
		personalisedparameterscontentstoreLocalService personalisedparameterscontentstoreLocalService) {
		this.personalisedparameterscontentstoreLocalService = personalisedparameterscontentstoreLocalService;
	}

	/**
	 * Returns the personalisedparameterscontentstore persistence.
	 *
	 * @return the personalisedparameterscontentstore persistence
	 */
	public personalisedparameterscontentstorePersistence getpersonalisedparameterscontentstorePersistence() {
		return personalisedparameterscontentstorePersistence;
	}

	/**
	 * Sets the personalisedparameterscontentstore persistence.
	 *
	 * @param personalisedparameterscontentstorePersistence the personalisedparameterscontentstore persistence
	 */
	public void setpersonalisedparameterscontentstorePersistence(
		personalisedparameterscontentstorePersistence personalisedparameterscontentstorePersistence) {
		this.personalisedparameterscontentstorePersistence = personalisedparameterscontentstorePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.chola.ppcontent.model.personalisedparameterscontentstore",
			personalisedparameterscontentstoreLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.chola.ppcontent.model.personalisedparameterscontentstore");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return personalisedparameterscontentstoreLocalService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return personalisedparameterscontentstore.class;
	}

	protected String getModelClassName() {
		return personalisedparameterscontentstore.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = personalisedparameterscontentstorePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.chola.ppcontent.service.contentuniqueinformationLocalService.class)
	protected com.chola.ppcontent.service.contentuniqueinformationLocalService contentuniqueinformationLocalService;
	@BeanReference(type = contentuniqueinformationPersistence.class)
	protected contentuniqueinformationPersistence contentuniqueinformationPersistence;
	@BeanReference(type = com.chola.ppcontent.service.contentupdateLocalService.class)
	protected com.chola.ppcontent.service.contentupdateLocalService contentupdateLocalService;
	@BeanReference(type = contentupdatePersistence.class)
	protected contentupdatePersistence contentupdatePersistence;
	@BeanReference(type = contentupdateFinder.class)
	protected contentupdateFinder contentupdateFinder;
	@BeanReference(type = personalisedparameterscontentstoreLocalService.class)
	protected personalisedparameterscontentstoreLocalService personalisedparameterscontentstoreLocalService;
	@BeanReference(type = personalisedparameterscontentstorePersistence.class)
	protected personalisedparameterscontentstorePersistence personalisedparameterscontentstorePersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private personalisedparameterscontentstoreLocalServiceClpInvoker _clpInvoker =
		new personalisedparameterscontentstoreLocalServiceClpInvoker();
}