/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.feedforward.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the feedforwardgallery service. Represents a row in the &quot;chola_feedforwardgallery&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.feedforward.model.impl.feedforwardgalleryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.feedforward.model.impl.feedforwardgalleryImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see feedforwardgallery
 * @see com.chola.feedforward.model.impl.feedforwardgalleryImpl
 * @see com.chola.feedforward.model.impl.feedforwardgalleryModelImpl
 * @generated
 */
@ProviderType
public interface feedforwardgalleryModel extends BaseModel<feedforwardgallery> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a feedforwardgallery model instance should use the {@link feedforwardgallery} interface instead.
	 */

	/**
	 * Returns the primary key of this feedforwardgallery.
	 *
	 * @return the primary key of this feedforwardgallery
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this feedforwardgallery.
	 *
	 * @param primaryKey the primary key of this feedforwardgallery
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this feedforwardgallery.
	 *
	 * @return the ID of this feedforwardgallery
	 */
	public long getId();

	/**
	 * Sets the ID of this feedforwardgallery.
	 *
	 * @param id the ID of this feedforwardgallery
	 */
	public void setId(long id);

	/**
	 * Returns the album name of this feedforwardgallery.
	 *
	 * @return the album name of this feedforwardgallery
	 */
	@AutoEscape
	public String getAlbumName();

	/**
	 * Sets the album name of this feedforwardgallery.
	 *
	 * @param albumName the album name of this feedforwardgallery
	 */
	public void setAlbumName(String albumName);

	/**
	 * Returns the album desc of this feedforwardgallery.
	 *
	 * @return the album desc of this feedforwardgallery
	 */
	@AutoEscape
	public String getAlbumDesc();

	/**
	 * Sets the album desc of this feedforwardgallery.
	 *
	 * @param albumDesc the album desc of this feedforwardgallery
	 */
	public void setAlbumDesc(String albumDesc);

	/**
	 * Returns the album ID of this feedforwardgallery.
	 *
	 * @return the album ID of this feedforwardgallery
	 */
	@AutoEscape
	public String getAlbumId();

	/**
	 * Sets the album ID of this feedforwardgallery.
	 *
	 * @param albumId the album ID of this feedforwardgallery
	 */
	public void setAlbumId(String albumId);

	/**
	 * Returns the created date of this feedforwardgallery.
	 *
	 * @return the created date of this feedforwardgallery
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this feedforwardgallery.
	 *
	 * @param createdDate the created date of this feedforwardgallery
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this feedforwardgallery.
	 *
	 * @return the created by of this feedforwardgallery
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this feedforwardgallery.
	 *
	 * @param createdBy the created by of this feedforwardgallery
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated date of this feedforwardgallery.
	 *
	 * @return the updated date of this feedforwardgallery
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this feedforwardgallery.
	 *
	 * @param updatedDate the updated date of this feedforwardgallery
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the updated by of this feedforwardgallery.
	 *
	 * @return the updated by of this feedforwardgallery
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this feedforwardgallery.
	 *
	 * @param updatedBy the updated by of this feedforwardgallery
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the flag of this feedforwardgallery.
	 *
	 * @return the flag of this feedforwardgallery
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this feedforwardgallery.
	 *
	 * @param flag the flag of this feedforwardgallery
	 */
	public void setFlag(String flag);

	/**
	 * Returns the content_id of this feedforwardgallery.
	 *
	 * @return the content_id of this feedforwardgallery
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this feedforwardgallery.
	 *
	 * @param content_id the content_id of this feedforwardgallery
	 */
	public void setContent_id(long content_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.feedforward.model.feedforwardgallery feedforwardgallery);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.feedforward.model.feedforwardgallery> toCacheModel();

	@Override
	public com.chola.feedforward.model.feedforwardgallery toEscapedModel();

	@Override
	public com.chola.feedforward.model.feedforwardgallery toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}