/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the cholatalkiespath service. Represents a row in the &quot;CholaT_cholatalkiespath&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.model.impl.cholatalkiespathModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.model.impl.cholatalkiespathImpl}.
 * </p>
 *
 * @author adms.java1
 * @see cholatalkiespath
 * @see com.model.impl.cholatalkiespathImpl
 * @see com.model.impl.cholatalkiespathModelImpl
 * @generated
 */
@ProviderType
public interface cholatalkiespathModel extends BaseModel<cholatalkiespath> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cholatalkiespath model instance should use the {@link cholatalkiespath} interface instead.
	 */

	/**
	 * Returns the primary key of this cholatalkiespath.
	 *
	 * @return the primary key of this cholatalkiespath
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cholatalkiespath.
	 *
	 * @param primaryKey the primary key of this cholatalkiespath
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this cholatalkiespath.
	 *
	 * @return the ID of this cholatalkiespath
	 */
	public long getId();

	/**
	 * Sets the ID of this cholatalkiespath.
	 *
	 * @param id the ID of this cholatalkiespath
	 */
	public void setId(long id);

	/**
	 * Returns the cholatalkiesdetaild_id of this cholatalkiespath.
	 *
	 * @return the cholatalkiesdetaild_id of this cholatalkiespath
	 */
	@AutoEscape
	public String getCholatalkiesdetaild_id();

	/**
	 * Sets the cholatalkiesdetaild_id of this cholatalkiespath.
	 *
	 * @param cholatalkiesdetaild_id the cholatalkiesdetaild_id of this cholatalkiespath
	 */
	public void setCholatalkiesdetaild_id(String cholatalkiesdetaild_id);

	/**
	 * Returns the content_id of this cholatalkiespath.
	 *
	 * @return the content_id of this cholatalkiespath
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this cholatalkiespath.
	 *
	 * @param content_id the content_id of this cholatalkiespath
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the video path of this cholatalkiespath.
	 *
	 * @return the video path of this cholatalkiespath
	 */
	@AutoEscape
	public String getVideoPath();

	/**
	 * Sets the video path of this cholatalkiespath.
	 *
	 * @param VideoPath the video path of this cholatalkiespath
	 */
	public void setVideoPath(String VideoPath);

	/**
	 * Returns the video title of this cholatalkiespath.
	 *
	 * @return the video title of this cholatalkiespath
	 */
	@AutoEscape
	public String getVideoTitle();

	/**
	 * Sets the video title of this cholatalkiespath.
	 *
	 * @param videoTitle the video title of this cholatalkiespath
	 */
	public void setVideoTitle(String videoTitle);

	/**
	 * Returns the video desc of this cholatalkiespath.
	 *
	 * @return the video desc of this cholatalkiespath
	 */
	@AutoEscape
	public String getVideoDesc();

	/**
	 * Sets the video desc of this cholatalkiespath.
	 *
	 * @param videoDesc the video desc of this cholatalkiespath
	 */
	public void setVideoDesc(String videoDesc);

	/**
	 * Returns the created date of this cholatalkiespath.
	 *
	 * @return the created date of this cholatalkiespath
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this cholatalkiespath.
	 *
	 * @param createdDate the created date of this cholatalkiespath
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this cholatalkiespath.
	 *
	 * @return the created by of this cholatalkiespath
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this cholatalkiespath.
	 *
	 * @param createdBy the created by of this cholatalkiespath
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated date of this cholatalkiespath.
	 *
	 * @return the updated date of this cholatalkiespath
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this cholatalkiespath.
	 *
	 * @param updatedDate the updated date of this cholatalkiespath
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the updated by of this cholatalkiespath.
	 *
	 * @return the updated by of this cholatalkiespath
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this cholatalkiespath.
	 *
	 * @param updatedBy the updated by of this cholatalkiespath
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the flag of this cholatalkiespath.
	 *
	 * @return the flag of this cholatalkiespath
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this cholatalkiespath.
	 *
	 * @param flag the flag of this cholatalkiespath
	 */
	public void setFlag(String flag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.model.cholatalkiespath cholatalkiespath);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.model.cholatalkiespath> toCacheModel();

	@Override
	public com.model.cholatalkiespath toEscapedModel();

	@Override
	public com.model.cholatalkiespath toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}