/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.usertheme.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the themecolor service. Represents a row in the &quot;usertheme_themecolor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.usertheme.model.impl.themecolorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.usertheme.model.impl.themecolorImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see themecolor
 * @see com.usertheme.model.impl.themecolorImpl
 * @see com.usertheme.model.impl.themecolorModelImpl
 * @generated
 */
@ProviderType
public interface themecolorModel extends BaseModel<themecolor> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a themecolor model instance should use the {@link themecolor} interface instead.
	 */

	/**
	 * Returns the primary key of this themecolor.
	 *
	 * @return the primary key of this themecolor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this themecolor.
	 *
	 * @param primaryKey the primary key of this themecolor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this themecolor.
	 *
	 * @return the ID of this themecolor
	 */
	public long getId();

	/**
	 * Sets the ID of this themecolor.
	 *
	 * @param id the ID of this themecolor
	 */
	public void setId(long id);

	/**
	 * Returns the user_id of this themecolor.
	 *
	 * @return the user_id of this themecolor
	 */
	@AutoEscape
	public String getUser_id();

	/**
	 * Sets the user_id of this themecolor.
	 *
	 * @param user_id the user_id of this themecolor
	 */
	public void setUser_id(String user_id);

	/**
	 * Returns the color of this themecolor.
	 *
	 * @return the color of this themecolor
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this themecolor.
	 *
	 * @param color the color of this themecolor
	 */
	public void setColor(String color);

	/**
	 * Returns the updated date of this themecolor.
	 *
	 * @return the updated date of this themecolor
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this themecolor.
	 *
	 * @param updatedDate the updated date of this themecolor
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.usertheme.model.themecolor themecolor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.usertheme.model.themecolor> toCacheModel();

	@Override
	public com.usertheme.model.themecolor toEscapedModel();

	@Override
	public com.usertheme.model.themecolor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}