/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.birthday.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the predefinedmessages service. Represents a row in the &quot;Add_predefinedmessages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.birthday.model.impl.predefinedmessagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.birthday.model.impl.predefinedmessagesImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see predefinedmessages
 * @see com.chola.birthday.model.impl.predefinedmessagesImpl
 * @see com.chola.birthday.model.impl.predefinedmessagesModelImpl
 * @generated
 */
@ProviderType
public interface predefinedmessagesModel extends BaseModel<predefinedmessages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a predefinedmessages model instance should use the {@link predefinedmessages} interface instead.
	 */

	/**
	 * Returns the primary key of this predefinedmessages.
	 *
	 * @return the primary key of this predefinedmessages
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this predefinedmessages.
	 *
	 * @param primaryKey the primary key of this predefinedmessages
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this predefinedmessages.
	 *
	 * @return the ID of this predefinedmessages
	 */
	public long getId();

	/**
	 * Sets the ID of this predefinedmessages.
	 *
	 * @param id the ID of this predefinedmessages
	 */
	public void setId(long id);

	/**
	 * Returns the message of this predefinedmessages.
	 *
	 * @return the message of this predefinedmessages
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this predefinedmessages.
	 *
	 * @param message the message of this predefinedmessages
	 */
	public void setMessage(String message);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.birthday.model.predefinedmessages predefinedmessages);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.birthday.model.predefinedmessages> toCacheModel();

	@Override
	public com.chola.birthday.model.predefinedmessages toEscapedModel();

	@Override
	public com.chola.birthday.model.predefinedmessages toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}