/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.videogallery.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the videogallerypath service. Represents a row in the &quot;cholav_videogallerypath&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.videogallery.model.impl.videogallerypathModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.videogallery.model.impl.videogallerypathImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see videogallerypath
 * @see com.chola.videogallery.model.impl.videogallerypathImpl
 * @see com.chola.videogallery.model.impl.videogallerypathModelImpl
 * @generated
 */
@ProviderType
public interface videogallerypathModel extends BaseModel<videogallerypath> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a videogallerypath model instance should use the {@link videogallerypath} interface instead.
	 */

	/**
	 * Returns the primary key of this videogallerypath.
	 *
	 * @return the primary key of this videogallerypath
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this videogallerypath.
	 *
	 * @param primaryKey the primary key of this videogallerypath
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this videogallerypath.
	 *
	 * @return the ID of this videogallerypath
	 */
	public long getId();

	/**
	 * Sets the ID of this videogallerypath.
	 *
	 * @param id the ID of this videogallerypath
	 */
	public void setId(long id);

	/**
	 * Returns the album ID of this videogallerypath.
	 *
	 * @return the album ID of this videogallerypath
	 */
	@AutoEscape
	public String getAlbumId();

	/**
	 * Sets the album ID of this videogallerypath.
	 *
	 * @param albumId the album ID of this videogallerypath
	 */
	public void setAlbumId(String albumId);

	/**
	 * Returns the content_id of this videogallerypath.
	 *
	 * @return the content_id of this videogallerypath
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this videogallerypath.
	 *
	 * @param content_id the content_id of this videogallerypath
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the album video path of this videogallerypath.
	 *
	 * @return the album video path of this videogallerypath
	 */
	@AutoEscape
	public String getAlbumVideoPath();

	/**
	 * Sets the album video path of this videogallerypath.
	 *
	 * @param albumVideoPath the album video path of this videogallerypath
	 */
	public void setAlbumVideoPath(String albumVideoPath);

	/**
	 * Returns the created date of this videogallerypath.
	 *
	 * @return the created date of this videogallerypath
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this videogallerypath.
	 *
	 * @param createdDate the created date of this videogallerypath
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this videogallerypath.
	 *
	 * @return the created by of this videogallerypath
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this videogallerypath.
	 *
	 * @param createdBy the created by of this videogallerypath
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated date of this videogallerypath.
	 *
	 * @return the updated date of this videogallerypath
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this videogallerypath.
	 *
	 * @param updatedDate the updated date of this videogallerypath
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the updated by of this videogallerypath.
	 *
	 * @return the updated by of this videogallerypath
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this videogallerypath.
	 *
	 * @param updatedBy the updated by of this videogallerypath
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the flag of this videogallerypath.
	 *
	 * @return the flag of this videogallerypath
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this videogallerypath.
	 *
	 * @param flag the flag of this videogallerypath
	 */
	public void setFlag(String flag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.videogallery.model.videogallerypath videogallerypath);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.videogallery.model.videogallerypath> toCacheModel();

	@Override
	public com.chola.videogallery.model.videogallerypath toEscapedModel();

	@Override
	public com.chola.videogallery.model.videogallerypath toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}