/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.mdspeak.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.chola.mdspeak.model.MdSpeaks;
import com.chola.mdspeak.model.MdSpeaksModel;
import com.chola.mdspeak.model.MdSpeaksSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MdSpeaks service. Represents a row in the &quot;mdspeak_MdSpeaks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MdSpeaksModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MdSpeaksImpl}.
 * </p>
 *
 * @author adms.java1
 * @see MdSpeaksImpl
 * @see MdSpeaks
 * @see MdSpeaksModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MdSpeaksModelImpl extends BaseModelImpl<MdSpeaks>
	implements MdSpeaksModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a md speaks model instance should use the {@link MdSpeaks} interface instead.
	 */
	public static final String TABLE_NAME = "mdspeak_MdSpeaks";
	public static final Object[][] TABLE_COLUMNS = {
			{ "Id", Types.BIGINT },
			{ "username", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("username", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table mdspeak_MdSpeaks (Id LONG not null primary key,username VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table mdspeak_MdSpeaks";
	public static final String ORDER_BY_JPQL = " ORDER BY mdSpeaks.Id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY mdspeak_MdSpeaks.Id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.chola.mdspeak.model.MdSpeaks"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.chola.mdspeak.model.MdSpeaks"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MdSpeaks toModel(MdSpeaksSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MdSpeaks model = new MdSpeaksImpl();

		model.setId(soapModel.getId());
		model.setUsername(soapModel.getUsername());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MdSpeaks> toModels(MdSpeaksSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MdSpeaks> models = new ArrayList<MdSpeaks>(soapModels.length);

		for (MdSpeaksSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.chola.mdspeak.model.MdSpeaks"));

	public MdSpeaksModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MdSpeaks.class;
	}

	@Override
	public String getModelClassName() {
		return MdSpeaks.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("Id", getId());
		attributes.put("username", getUsername());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long Id = (Long)attributes.get("Id");

		if (Id != null) {
			setId(Id);
		}

		String username = (String)attributes.get("username");

		if (username != null) {
			setUsername(username);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@JSON
	@Override
	public String getUsername() {
		if (_username == null) {
			return StringPool.BLANK;
		}
		else {
			return _username;
		}
	}

	@Override
	public void setUsername(String username) {
		_username = username;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MdSpeaks.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MdSpeaks toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MdSpeaks)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MdSpeaksImpl mdSpeaksImpl = new MdSpeaksImpl();

		mdSpeaksImpl.setId(getId());
		mdSpeaksImpl.setUsername(getUsername());

		mdSpeaksImpl.resetOriginalValues();

		return mdSpeaksImpl;
	}

	@Override
	public int compareTo(MdSpeaks mdSpeaks) {
		long primaryKey = mdSpeaks.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MdSpeaks)) {
			return false;
		}

		MdSpeaks mdSpeaks = (MdSpeaks)obj;

		long primaryKey = mdSpeaks.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<MdSpeaks> toCacheModel() {
		MdSpeaksCacheModel mdSpeaksCacheModel = new MdSpeaksCacheModel();

		mdSpeaksCacheModel.Id = getId();

		mdSpeaksCacheModel.username = getUsername();

		String username = mdSpeaksCacheModel.username;

		if ((username != null) && (username.length() == 0)) {
			mdSpeaksCacheModel.username = null;
		}

		return mdSpeaksCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{Id=");
		sb.append(getId());
		sb.append(", username=");
		sb.append(getUsername());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.chola.mdspeak.model.MdSpeaks");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>Id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>username</column-name><column-value><![CDATA[");
		sb.append(getUsername());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MdSpeaks.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MdSpeaks.class
		};
	private long _Id;
	private String _username;
	private MdSpeaks _escapedModel;
}