/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.businessmis.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the businessmisdetails service. Represents a row in the &quot;chola_businessmisdetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.businessmis.model.impl.businessmisdetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.businessmis.model.impl.businessmisdetailsImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see businessmisdetails
 * @see com.chola.businessmis.model.impl.businessmisdetailsImpl
 * @see com.chola.businessmis.model.impl.businessmisdetailsModelImpl
 * @generated
 */
@ProviderType
public interface businessmisdetailsModel extends BaseModel<businessmisdetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a businessmisdetails model instance should use the {@link businessmisdetails} interface instead.
	 */

	/**
	 * Returns the primary key of this businessmisdetails.
	 *
	 * @return the primary key of this businessmisdetails
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this businessmisdetails.
	 *
	 * @param primaryKey the primary key of this businessmisdetails
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this businessmisdetails.
	 *
	 * @return the ID of this businessmisdetails
	 */
	public long getId();

	/**
	 * Sets the ID of this businessmisdetails.
	 *
	 * @param id the ID of this businessmisdetails
	 */
	public void setId(long id);

	/**
	 * Returns the content_id of this businessmisdetails.
	 *
	 * @return the content_id of this businessmisdetails
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this businessmisdetails.
	 *
	 * @param content_id the content_id of this businessmisdetails
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the businesstitle of this businessmisdetails.
	 *
	 * @return the businesstitle of this businessmisdetails
	 */
	@AutoEscape
	public String getBusinesstitle();

	/**
	 * Sets the businesstitle of this businessmisdetails.
	 *
	 * @param businesstitle the businesstitle of this businessmisdetails
	 */
	public void setBusinesstitle(String businesstitle);

	/**
	 * Returns the business desc of this businessmisdetails.
	 *
	 * @return the business desc of this businessmisdetails
	 */
	@AutoEscape
	public String getBusinessDesc();

	/**
	 * Sets the business desc of this businessmisdetails.
	 *
	 * @param businessDesc the business desc of this businessmisdetails
	 */
	public void setBusinessDesc(String businessDesc);

	/**
	 * Returns the business link of this businessmisdetails.
	 *
	 * @return the business link of this businessmisdetails
	 */
	@AutoEscape
	public String getBusinessLink();

	/**
	 * Sets the business link of this businessmisdetails.
	 *
	 * @param businessLink the business link of this businessmisdetails
	 */
	public void setBusinessLink(String businessLink);

	/**
	 * Returns the filepath of this businessmisdetails.
	 *
	 * @return the filepath of this businessmisdetails
	 */
	@AutoEscape
	public String getFilepath();

	/**
	 * Sets the filepath of this businessmisdetails.
	 *
	 * @param filepath the filepath of this businessmisdetails
	 */
	public void setFilepath(String filepath);

	/**
	 * Returns the filename of this businessmisdetails.
	 *
	 * @return the filename of this businessmisdetails
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this businessmisdetails.
	 *
	 * @param filename the filename of this businessmisdetails
	 */
	public void setFilename(String filename);

	/**
	 * Returns the created date of this businessmisdetails.
	 *
	 * @return the created date of this businessmisdetails
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this businessmisdetails.
	 *
	 * @param createdDate the created date of this businessmisdetails
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this businessmisdetails.
	 *
	 * @return the created by of this businessmisdetails
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this businessmisdetails.
	 *
	 * @param createdBy the created by of this businessmisdetails
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this businessmisdetails.
	 *
	 * @return the modified date of this businessmisdetails
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this businessmisdetails.
	 *
	 * @param modifiedDate the modified date of this businessmisdetails
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this businessmisdetails.
	 *
	 * @return the modified by of this businessmisdetails
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this businessmisdetails.
	 *
	 * @param modifiedBy the modified by of this businessmisdetails
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the flag of this businessmisdetails.
	 *
	 * @return the flag of this businessmisdetails
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this businessmisdetails.
	 *
	 * @param flag the flag of this businessmisdetails
	 */
	public void setFlag(String flag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.businessmis.model.businessmisdetails businessmisdetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.businessmis.model.businessmisdetails> toCacheModel();

	@Override
	public com.chola.businessmis.model.businessmisdetails toEscapedModel();

	@Override
	public com.chola.businessmis.model.businessmisdetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}