/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.businessmis.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the businessmisusers service. Represents a row in the &quot;chola_businessmisusers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.businessmis.model.impl.businessmisusersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.businessmis.model.impl.businessmisusersImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see businessmisusers
 * @see com.chola.businessmis.model.impl.businessmisusersImpl
 * @see com.chola.businessmis.model.impl.businessmisusersModelImpl
 * @generated
 */
@ProviderType
public interface businessmisusersModel extends BaseModel<businessmisusers> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a businessmisusers model instance should use the {@link businessmisusers} interface instead.
	 */

	/**
	 * Returns the primary key of this businessmisusers.
	 *
	 * @return the primary key of this businessmisusers
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this businessmisusers.
	 *
	 * @param primaryKey the primary key of this businessmisusers
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this businessmisusers.
	 *
	 * @return the ID of this businessmisusers
	 */
	public long getId();

	/**
	 * Sets the ID of this businessmisusers.
	 *
	 * @param id the ID of this businessmisusers
	 */
	public void setId(long id);

	/**
	 * Returns the user_id of this businessmisusers.
	 *
	 * @return the user_id of this businessmisusers
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this businessmisusers.
	 *
	 * @param user_id the user_id of this businessmisusers
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the businessdetails_id of this businessmisusers.
	 *
	 * @return the businessdetails_id of this businessmisusers
	 */
	public long getBusinessdetails_id();

	/**
	 * Sets the businessdetails_id of this businessmisusers.
	 *
	 * @param businessdetails_id the businessdetails_id of this businessmisusers
	 */
	public void setBusinessdetails_id(long businessdetails_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.businessmis.model.businessmisusers businessmisusers);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.businessmis.model.businessmisusers> toCacheModel();

	@Override
	public com.chola.businessmis.model.businessmisusers toEscapedModel();

	@Override
	public com.chola.businessmis.model.businessmisusers toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}