/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.imagegallery.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.chola.imagegallery.model.imagegallerypath;
import com.chola.imagegallery.model.imagegallerypathModel;
import com.chola.imagegallery.model.imagegallerypathSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the imagegallerypath service. Represents a row in the &quot;cholam_imagegallerypath&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link imagegallerypathModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link imagegallerypathImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see imagegallerypathImpl
 * @see imagegallerypath
 * @see imagegallerypathModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class imagegallerypathModelImpl extends BaseModelImpl<imagegallerypath>
	implements imagegallerypathModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a imagegallerypath model instance should use the {@link imagegallerypath} interface instead.
	 */
	public static final String TABLE_NAME = "cholam_imagegallerypath";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "albumId", Types.VARCHAR },
			{ "content_id", Types.BIGINT },
			{ "albumImagePath", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdBy", Types.VARCHAR },
			{ "updatedDate", Types.TIMESTAMP },
			{ "updatedBy", Types.VARCHAR },
			{ "flag", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("albumId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("albumImagePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("updatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("flag", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table cholam_imagegallerypath (id_ LONG not null primary key,albumId VARCHAR(75) null,content_id LONG,albumImagePath TEXT null,createdDate DATE null,createdBy VARCHAR(75) null,updatedDate DATE null,updatedBy VARCHAR(75) null,flag VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table cholam_imagegallerypath";
	public static final String ORDER_BY_JPQL = " ORDER BY imagegallerypath.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY cholam_imagegallerypath.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.chola.imagegallery.model.imagegallerypath"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.chola.imagegallery.model.imagegallerypath"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.chola.imagegallery.model.imagegallerypath"),
			true);
	public static final long ALBUMID_COLUMN_BITMASK = 1L;
	public static final long CREATEDDATE_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static imagegallerypath toModel(imagegallerypathSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		imagegallerypath model = new imagegallerypathImpl();

		model.setId(soapModel.getId());
		model.setAlbumId(soapModel.getAlbumId());
		model.setContent_id(soapModel.getContent_id());
		model.setAlbumImagePath(soapModel.getAlbumImagePath());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedDate(soapModel.getUpdatedDate());
		model.setUpdatedBy(soapModel.getUpdatedBy());
		model.setFlag(soapModel.getFlag());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<imagegallerypath> toModels(
		imagegallerypathSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<imagegallerypath> models = new ArrayList<imagegallerypath>(soapModels.length);

		for (imagegallerypathSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.chola.imagegallery.model.imagegallerypath"));

	public imagegallerypathModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return imagegallerypath.class;
	}

	@Override
	public String getModelClassName() {
		return imagegallerypath.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("albumId", getAlbumId());
		attributes.put("content_id", getContent_id());
		attributes.put("albumImagePath", getAlbumImagePath());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedDate", getUpdatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("flag", getFlag());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String albumId = (String)attributes.get("albumId");

		if (albumId != null) {
			setAlbumId(albumId);
		}

		Long content_id = (Long)attributes.get("content_id");

		if (content_id != null) {
			setContent_id(content_id);
		}

		String albumImagePath = (String)attributes.get("albumImagePath");

		if (albumImagePath != null) {
			setAlbumImagePath(albumImagePath);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		String flag = (String)attributes.get("flag");

		if (flag != null) {
			setFlag(flag);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getAlbumId() {
		if (_albumId == null) {
			return StringPool.BLANK;
		}
		else {
			return _albumId;
		}
	}

	@Override
	public void setAlbumId(String albumId) {
		_columnBitmask |= ALBUMID_COLUMN_BITMASK;

		if (_originalAlbumId == null) {
			_originalAlbumId = _albumId;
		}

		_albumId = albumId;
	}

	public String getOriginalAlbumId() {
		return GetterUtil.getString(_originalAlbumId);
	}

	@JSON
	@Override
	public long getContent_id() {
		return _content_id;
	}

	@Override
	public void setContent_id(long content_id) {
		_content_id = content_id;
	}

	@JSON
	@Override
	public String getAlbumImagePath() {
		if (_albumImagePath == null) {
			return StringPool.BLANK;
		}
		else {
			return _albumImagePath;
		}
	}

	@Override
	public void setAlbumImagePath(String albumImagePath) {
		_albumImagePath = albumImagePath;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@JSON
	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@JSON
	@Override
	public String getFlag() {
		if (_flag == null) {
			return StringPool.BLANK;
		}
		else {
			return _flag;
		}
	}

	@Override
	public void setFlag(String flag) {
		_flag = flag;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			imagegallerypath.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public imagegallerypath toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (imagegallerypath)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		imagegallerypathImpl imagegallerypathImpl = new imagegallerypathImpl();

		imagegallerypathImpl.setId(getId());
		imagegallerypathImpl.setAlbumId(getAlbumId());
		imagegallerypathImpl.setContent_id(getContent_id());
		imagegallerypathImpl.setAlbumImagePath(getAlbumImagePath());
		imagegallerypathImpl.setCreatedDate(getCreatedDate());
		imagegallerypathImpl.setCreatedBy(getCreatedBy());
		imagegallerypathImpl.setUpdatedDate(getUpdatedDate());
		imagegallerypathImpl.setUpdatedBy(getUpdatedBy());
		imagegallerypathImpl.setFlag(getFlag());

		imagegallerypathImpl.resetOriginalValues();

		return imagegallerypathImpl;
	}

	@Override
	public int compareTo(imagegallerypath imagegallerypath) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				imagegallerypath.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof imagegallerypath)) {
			return false;
		}

		imagegallerypath imagegallerypath = (imagegallerypath)obj;

		long primaryKey = imagegallerypath.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		imagegallerypathModelImpl imagegallerypathModelImpl = this;

		imagegallerypathModelImpl._originalAlbumId = imagegallerypathModelImpl._albumId;

		imagegallerypathModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<imagegallerypath> toCacheModel() {
		imagegallerypathCacheModel imagegallerypathCacheModel = new imagegallerypathCacheModel();

		imagegallerypathCacheModel.id = getId();

		imagegallerypathCacheModel.albumId = getAlbumId();

		String albumId = imagegallerypathCacheModel.albumId;

		if ((albumId != null) && (albumId.length() == 0)) {
			imagegallerypathCacheModel.albumId = null;
		}

		imagegallerypathCacheModel.content_id = getContent_id();

		imagegallerypathCacheModel.albumImagePath = getAlbumImagePath();

		String albumImagePath = imagegallerypathCacheModel.albumImagePath;

		if ((albumImagePath != null) && (albumImagePath.length() == 0)) {
			imagegallerypathCacheModel.albumImagePath = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			imagegallerypathCacheModel.createdDate = createdDate.getTime();
		}
		else {
			imagegallerypathCacheModel.createdDate = Long.MIN_VALUE;
		}

		imagegallerypathCacheModel.createdBy = getCreatedBy();

		String createdBy = imagegallerypathCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			imagegallerypathCacheModel.createdBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			imagegallerypathCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			imagegallerypathCacheModel.updatedDate = Long.MIN_VALUE;
		}

		imagegallerypathCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = imagegallerypathCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			imagegallerypathCacheModel.updatedBy = null;
		}

		imagegallerypathCacheModel.flag = getFlag();

		String flag = imagegallerypathCacheModel.flag;

		if ((flag != null) && (flag.length() == 0)) {
			imagegallerypathCacheModel.flag = null;
		}

		return imagegallerypathCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", albumId=");
		sb.append(getAlbumId());
		sb.append(", content_id=");
		sb.append(getContent_id());
		sb.append(", albumImagePath=");
		sb.append(getAlbumImagePath());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", flag=");
		sb.append(getFlag());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.chola.imagegallery.model.imagegallerypath");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>albumId</column-name><column-value><![CDATA[");
		sb.append(getAlbumId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content_id</column-name><column-value><![CDATA[");
		sb.append(getContent_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>albumImagePath</column-name><column-value><![CDATA[");
		sb.append(getAlbumImagePath());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flag</column-name><column-value><![CDATA[");
		sb.append(getFlag());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = imagegallerypath.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			imagegallerypath.class
		};
	private long _id;
	private String _albumId;
	private String _originalAlbumId;
	private long _content_id;
	private String _albumImagePath;
	private Date _createdDate;
	private String _createdBy;
	private Date _updatedDate;
	private String _updatedBy;
	private String _flag;
	private long _columnBitmask;
	private imagegallerypath _escapedModel;
}