/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.calendar.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the data service. Represents a row in the &quot;events_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.calendar.model.impl.dataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.calendar.model.impl.dataImpl}.
 * </p>
 *
 * @author adms.java1
 * @see data
 * @see com.chola.calendar.model.impl.dataImpl
 * @see com.chola.calendar.model.impl.dataModelImpl
 * @generated
 */
@ProviderType
public interface dataModel extends BaseModel<data> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data model instance should use the {@link data} interface instead.
	 */

	/**
	 * Returns the primary key of this data.
	 *
	 * @return the primary key of this data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data.
	 *
	 * @param primaryKey the primary key of this data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the eventid of this data.
	 *
	 * @return the eventid of this data
	 */
	public long getEventid();

	/**
	 * Sets the eventid of this data.
	 *
	 * @param eventid the eventid of this data
	 */
	public void setEventid(long eventid);

	/**
	 * Returns the eventdetails of this data.
	 *
	 * @return the eventdetails of this data
	 */
	@AutoEscape
	public String getEventdetails();

	/**
	 * Sets the eventdetails of this data.
	 *
	 * @param eventdetails the eventdetails of this data
	 */
	public void setEventdetails(String eventdetails);

	/**
	 * Returns the eventfrom of this data.
	 *
	 * @return the eventfrom of this data
	 */
	@AutoEscape
	public String getEventfrom();

	/**
	 * Sets the eventfrom of this data.
	 *
	 * @param eventfrom the eventfrom of this data
	 */
	public void setEventfrom(String eventfrom);

	/**
	 * Returns the eventto of this data.
	 *
	 * @return the eventto of this data
	 */
	@AutoEscape
	public String getEventto();

	/**
	 * Sets the eventto of this data.
	 *
	 * @param eventto the eventto of this data
	 */
	public void setEventto(String eventto);

	/**
	 * Returns the location of this data.
	 *
	 * @return the location of this data
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this data.
	 *
	 * @param location the location of this data
	 */
	public void setLocation(String location);

	/**
	 * Returns the dept of this data.
	 *
	 * @return the dept of this data
	 */
	@AutoEscape
	public String getDept();

	/**
	 * Sets the dept of this data.
	 *
	 * @param dept the dept of this data
	 */
	public void setDept(String dept);

	/**
	 * Returns the subdept of this data.
	 *
	 * @return the subdept of this data
	 */
	@AutoEscape
	public String getSubdept();

	/**
	 * Sets the subdept of this data.
	 *
	 * @param subdept the subdept of this data
	 */
	public void setSubdept(String subdept);

	/**
	 * Returns the grade of this data.
	 *
	 * @return the grade of this data
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this data.
	 *
	 * @param grade the grade of this data
	 */
	public void setGrade(String grade);

	/**
	 * Returns the age of this data.
	 *
	 * @return the age of this data
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this data.
	 *
	 * @param age the age of this data
	 */
	public void setAge(String age);

	/**
	 * Returns the companyname of this data.
	 *
	 * @return the companyname of this data
	 */
	@AutoEscape
	public String getCompanyname();

	/**
	 * Sets the companyname of this data.
	 *
	 * @param companyname the companyname of this data
	 */
	public void setCompanyname(String companyname);

	/**
	 * Returns the userid of this data.
	 *
	 * @return the userid of this data
	 */
	@AutoEscape
	public String getUserid();

	/**
	 * Sets the userid of this data.
	 *
	 * @param userid the userid of this data
	 */
	public void setUserid(String userid);

	/**
	 * Returns the gender of this data.
	 *
	 * @return the gender of this data
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this data.
	 *
	 * @param gender the gender of this data
	 */
	public void setGender(String gender);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.chola.calendar.model.data data);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.calendar.model.data> toCacheModel();

	@Override
	public com.chola.calendar.model.data toEscapedModel();

	@Override
	public com.chola.calendar.model.data toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}