/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.shutterspeed.service.base;

import com.chola.shutterspeed.model.shutterspeedgalleryusers;
import com.chola.shutterspeed.service.persistence.shutterspeedgalleryFinder;
import com.chola.shutterspeed.service.persistence.shutterspeedgalleryPersistence;
import com.chola.shutterspeed.service.persistence.shutterspeedgallerypathPersistence;
import com.chola.shutterspeed.service.persistence.shutterspeedgalleryusersPersistence;
import com.chola.shutterspeed.service.shutterspeedgalleryusersService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the shutterspeedgalleryusers remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.chola.shutterspeed.service.impl.shutterspeedgalleryusersServiceImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see com.chola.shutterspeed.service.impl.shutterspeedgalleryusersServiceImpl
 * @see com.chola.shutterspeed.service.shutterspeedgalleryusersServiceUtil
 * @generated
 */
public abstract class shutterspeedgalleryusersServiceBaseImpl
	extends BaseServiceImpl implements shutterspeedgalleryusersService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.chola.shutterspeed.service.shutterspeedgalleryusersServiceUtil} to access the shutterspeedgalleryusers remote service.
	 */

	/**
	 * Returns the shutterspeedgallery local service.
	 *
	 * @return the shutterspeedgallery local service
	 */
	public com.chola.shutterspeed.service.shutterspeedgalleryLocalService getshutterspeedgalleryLocalService() {
		return shutterspeedgalleryLocalService;
	}

	/**
	 * Sets the shutterspeedgallery local service.
	 *
	 * @param shutterspeedgalleryLocalService the shutterspeedgallery local service
	 */
	public void setshutterspeedgalleryLocalService(
		com.chola.shutterspeed.service.shutterspeedgalleryLocalService shutterspeedgalleryLocalService) {
		this.shutterspeedgalleryLocalService = shutterspeedgalleryLocalService;
	}

	/**
	 * Returns the shutterspeedgallery remote service.
	 *
	 * @return the shutterspeedgallery remote service
	 */
	public com.chola.shutterspeed.service.shutterspeedgalleryService getshutterspeedgalleryService() {
		return shutterspeedgalleryService;
	}

	/**
	 * Sets the shutterspeedgallery remote service.
	 *
	 * @param shutterspeedgalleryService the shutterspeedgallery remote service
	 */
	public void setshutterspeedgalleryService(
		com.chola.shutterspeed.service.shutterspeedgalleryService shutterspeedgalleryService) {
		this.shutterspeedgalleryService = shutterspeedgalleryService;
	}

	/**
	 * Returns the shutterspeedgallery persistence.
	 *
	 * @return the shutterspeedgallery persistence
	 */
	public shutterspeedgalleryPersistence getshutterspeedgalleryPersistence() {
		return shutterspeedgalleryPersistence;
	}

	/**
	 * Sets the shutterspeedgallery persistence.
	 *
	 * @param shutterspeedgalleryPersistence the shutterspeedgallery persistence
	 */
	public void setshutterspeedgalleryPersistence(
		shutterspeedgalleryPersistence shutterspeedgalleryPersistence) {
		this.shutterspeedgalleryPersistence = shutterspeedgalleryPersistence;
	}

	/**
	 * Returns the shutterspeedgallery finder.
	 *
	 * @return the shutterspeedgallery finder
	 */
	public shutterspeedgalleryFinder getshutterspeedgalleryFinder() {
		return shutterspeedgalleryFinder;
	}

	/**
	 * Sets the shutterspeedgallery finder.
	 *
	 * @param shutterspeedgalleryFinder the shutterspeedgallery finder
	 */
	public void setshutterspeedgalleryFinder(
		shutterspeedgalleryFinder shutterspeedgalleryFinder) {
		this.shutterspeedgalleryFinder = shutterspeedgalleryFinder;
	}

	/**
	 * Returns the shutterspeedgallerypath local service.
	 *
	 * @return the shutterspeedgallerypath local service
	 */
	public com.chola.shutterspeed.service.shutterspeedgallerypathLocalService getshutterspeedgallerypathLocalService() {
		return shutterspeedgallerypathLocalService;
	}

	/**
	 * Sets the shutterspeedgallerypath local service.
	 *
	 * @param shutterspeedgallerypathLocalService the shutterspeedgallerypath local service
	 */
	public void setshutterspeedgallerypathLocalService(
		com.chola.shutterspeed.service.shutterspeedgallerypathLocalService shutterspeedgallerypathLocalService) {
		this.shutterspeedgallerypathLocalService = shutterspeedgallerypathLocalService;
	}

	/**
	 * Returns the shutterspeedgallerypath remote service.
	 *
	 * @return the shutterspeedgallerypath remote service
	 */
	public com.chola.shutterspeed.service.shutterspeedgallerypathService getshutterspeedgallerypathService() {
		return shutterspeedgallerypathService;
	}

	/**
	 * Sets the shutterspeedgallerypath remote service.
	 *
	 * @param shutterspeedgallerypathService the shutterspeedgallerypath remote service
	 */
	public void setshutterspeedgallerypathService(
		com.chola.shutterspeed.service.shutterspeedgallerypathService shutterspeedgallerypathService) {
		this.shutterspeedgallerypathService = shutterspeedgallerypathService;
	}

	/**
	 * Returns the shutterspeedgallerypath persistence.
	 *
	 * @return the shutterspeedgallerypath persistence
	 */
	public shutterspeedgallerypathPersistence getshutterspeedgallerypathPersistence() {
		return shutterspeedgallerypathPersistence;
	}

	/**
	 * Sets the shutterspeedgallerypath persistence.
	 *
	 * @param shutterspeedgallerypathPersistence the shutterspeedgallerypath persistence
	 */
	public void setshutterspeedgallerypathPersistence(
		shutterspeedgallerypathPersistence shutterspeedgallerypathPersistence) {
		this.shutterspeedgallerypathPersistence = shutterspeedgallerypathPersistence;
	}

	/**
	 * Returns the shutterspeedgalleryusers local service.
	 *
	 * @return the shutterspeedgalleryusers local service
	 */
	public com.chola.shutterspeed.service.shutterspeedgalleryusersLocalService getshutterspeedgalleryusersLocalService() {
		return shutterspeedgalleryusersLocalService;
	}

	/**
	 * Sets the shutterspeedgalleryusers local service.
	 *
	 * @param shutterspeedgalleryusersLocalService the shutterspeedgalleryusers local service
	 */
	public void setshutterspeedgalleryusersLocalService(
		com.chola.shutterspeed.service.shutterspeedgalleryusersLocalService shutterspeedgalleryusersLocalService) {
		this.shutterspeedgalleryusersLocalService = shutterspeedgalleryusersLocalService;
	}

	/**
	 * Returns the shutterspeedgalleryusers remote service.
	 *
	 * @return the shutterspeedgalleryusers remote service
	 */
	public shutterspeedgalleryusersService getshutterspeedgalleryusersService() {
		return shutterspeedgalleryusersService;
	}

	/**
	 * Sets the shutterspeedgalleryusers remote service.
	 *
	 * @param shutterspeedgalleryusersService the shutterspeedgalleryusers remote service
	 */
	public void setshutterspeedgalleryusersService(
		shutterspeedgalleryusersService shutterspeedgalleryusersService) {
		this.shutterspeedgalleryusersService = shutterspeedgalleryusersService;
	}

	/**
	 * Returns the shutterspeedgalleryusers persistence.
	 *
	 * @return the shutterspeedgalleryusers persistence
	 */
	public shutterspeedgalleryusersPersistence getshutterspeedgalleryusersPersistence() {
		return shutterspeedgalleryusersPersistence;
	}

	/**
	 * Sets the shutterspeedgalleryusers persistence.
	 *
	 * @param shutterspeedgalleryusersPersistence the shutterspeedgalleryusers persistence
	 */
	public void setshutterspeedgalleryusersPersistence(
		shutterspeedgalleryusersPersistence shutterspeedgalleryusersPersistence) {
		this.shutterspeedgalleryusersPersistence = shutterspeedgalleryusersPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return shutterspeedgalleryusersService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return shutterspeedgalleryusers.class;
	}

	protected String getModelClassName() {
		return shutterspeedgalleryusers.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = shutterspeedgalleryusersPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.chola.shutterspeed.service.shutterspeedgalleryLocalService.class)
	protected com.chola.shutterspeed.service.shutterspeedgalleryLocalService shutterspeedgalleryLocalService;
	@BeanReference(type = com.chola.shutterspeed.service.shutterspeedgalleryService.class)
	protected com.chola.shutterspeed.service.shutterspeedgalleryService shutterspeedgalleryService;
	@BeanReference(type = shutterspeedgalleryPersistence.class)
	protected shutterspeedgalleryPersistence shutterspeedgalleryPersistence;
	@BeanReference(type = shutterspeedgalleryFinder.class)
	protected shutterspeedgalleryFinder shutterspeedgalleryFinder;
	@BeanReference(type = com.chola.shutterspeed.service.shutterspeedgallerypathLocalService.class)
	protected com.chola.shutterspeed.service.shutterspeedgallerypathLocalService shutterspeedgallerypathLocalService;
	@BeanReference(type = com.chola.shutterspeed.service.shutterspeedgallerypathService.class)
	protected com.chola.shutterspeed.service.shutterspeedgallerypathService shutterspeedgallerypathService;
	@BeanReference(type = shutterspeedgallerypathPersistence.class)
	protected shutterspeedgallerypathPersistence shutterspeedgallerypathPersistence;
	@BeanReference(type = com.chola.shutterspeed.service.shutterspeedgalleryusersLocalService.class)
	protected com.chola.shutterspeed.service.shutterspeedgalleryusersLocalService shutterspeedgalleryusersLocalService;
	@BeanReference(type = shutterspeedgalleryusersService.class)
	protected shutterspeedgalleryusersService shutterspeedgalleryusersService;
	@BeanReference(type = shutterspeedgalleryusersPersistence.class)
	protected shutterspeedgalleryusersPersistence shutterspeedgalleryusersPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private shutterspeedgalleryusersServiceClpInvoker _clpInvoker = new shutterspeedgalleryusersServiceClpInvoker();
}