/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.book.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.chola.book.model.bookusers;
import com.chola.book.model.bookusersModel;
import com.chola.book.model.bookusersSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the bookusers service. Represents a row in the &quot;chola_bookusers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link bookusersModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link bookusersImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see bookusersImpl
 * @see bookusers
 * @see bookusersModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class bookusersModelImpl extends BaseModelImpl<bookusers>
	implements bookusersModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bookusers model instance should use the {@link bookusers} interface instead.
	 */
	public static final String TABLE_NAME = "chola_bookusers";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "user_id", Types.BIGINT },
			{ "book_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("user_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("book_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table chola_bookusers (id_ LONG not null primary key,user_id LONG,book_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table chola_bookusers";
	public static final String ORDER_BY_JPQL = " ORDER BY bookusers.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY chola_bookusers.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.chola.book.model.bookusers"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.chola.book.model.bookusers"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.chola.book.model.bookusers"),
			true);
	public static final long BOOK_ID_COLUMN_BITMASK = 1L;
	public static final long USER_ID_COLUMN_BITMASK = 2L;
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static bookusers toModel(bookusersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		bookusers model = new bookusersImpl();

		model.setId(soapModel.getId());
		model.setUser_id(soapModel.getUser_id());
		model.setBook_id(soapModel.getBook_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<bookusers> toModels(bookusersSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<bookusers> models = new ArrayList<bookusers>(soapModels.length);

		for (bookusersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.chola.book.model.bookusers"));

	public bookusersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return bookusers.class;
	}

	@Override
	public String getModelClassName() {
		return bookusers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("user_id", getUser_id());
		attributes.put("book_id", getBook_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long user_id = (Long)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		Long book_id = (Long)attributes.get("book_id");

		if (book_id != null) {
			setBook_id(book_id);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getUser_id() {
		return _user_id;
	}

	@Override
	public void setUser_id(long user_id) {
		_columnBitmask |= USER_ID_COLUMN_BITMASK;

		if (!_setOriginalUser_id) {
			_setOriginalUser_id = true;

			_originalUser_id = _user_id;
		}

		_user_id = user_id;
	}

	public long getOriginalUser_id() {
		return _originalUser_id;
	}

	@JSON
	@Override
	public long getBook_id() {
		return _book_id;
	}

	@Override
	public void setBook_id(long book_id) {
		_columnBitmask |= BOOK_ID_COLUMN_BITMASK;

		if (!_setOriginalBook_id) {
			_setOriginalBook_id = true;

			_originalBook_id = _book_id;
		}

		_book_id = book_id;
	}

	public long getOriginalBook_id() {
		return _originalBook_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			bookusers.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public bookusers toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (bookusers)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		bookusersImpl bookusersImpl = new bookusersImpl();

		bookusersImpl.setId(getId());
		bookusersImpl.setUser_id(getUser_id());
		bookusersImpl.setBook_id(getBook_id());

		bookusersImpl.resetOriginalValues();

		return bookusersImpl;
	}

	@Override
	public int compareTo(bookusers bookusers) {
		long primaryKey = bookusers.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof bookusers)) {
			return false;
		}

		bookusers bookusers = (bookusers)obj;

		long primaryKey = bookusers.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		bookusersModelImpl bookusersModelImpl = this;

		bookusersModelImpl._originalUser_id = bookusersModelImpl._user_id;

		bookusersModelImpl._setOriginalUser_id = false;

		bookusersModelImpl._originalBook_id = bookusersModelImpl._book_id;

		bookusersModelImpl._setOriginalBook_id = false;

		bookusersModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<bookusers> toCacheModel() {
		bookusersCacheModel bookusersCacheModel = new bookusersCacheModel();

		bookusersCacheModel.id = getId();

		bookusersCacheModel.user_id = getUser_id();

		bookusersCacheModel.book_id = getBook_id();

		return bookusersCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", book_id=");
		sb.append(getBook_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.chola.book.model.bookusers");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>book_id</column-name><column-value><![CDATA[");
		sb.append(getBook_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = bookusers.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			bookusers.class
		};
	private long _id;
	private long _user_id;
	private long _originalUser_id;
	private boolean _setOriginalUser_id;
	private long _book_id;
	private long _originalBook_id;
	private boolean _setOriginalBook_id;
	private long _columnBitmask;
	private bookusers _escapedModel;
}