/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.shutterspeed.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.chola.shutterspeed.model.shutterspeedgallery;
import com.chola.shutterspeed.model.shutterspeedgalleryModel;
import com.chola.shutterspeed.model.shutterspeedgallerySoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the shutterspeedgallery service. Represents a row in the &quot;chola_shutterspeedgallery&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link shutterspeedgalleryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link shutterspeedgalleryImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see shutterspeedgalleryImpl
 * @see shutterspeedgallery
 * @see shutterspeedgalleryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class shutterspeedgalleryModelImpl extends BaseModelImpl<shutterspeedgallery>
	implements shutterspeedgalleryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a shutterspeedgallery model instance should use the {@link shutterspeedgallery} interface instead.
	 */
	public static final String TABLE_NAME = "chola_shutterspeedgallery";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "albumName", Types.VARCHAR },
			{ "albumDesc", Types.VARCHAR },
			{ "albumId", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdBy", Types.VARCHAR },
			{ "updatedDate", Types.TIMESTAMP },
			{ "updatedBy", Types.VARCHAR },
			{ "flag", Types.VARCHAR },
			{ "content_id", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("albumName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("albumDesc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("albumId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("updatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("flag", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table chola_shutterspeedgallery (id_ LONG not null primary key,albumName VARCHAR(100) null,albumDesc VARCHAR(500) null,albumId VARCHAR(75) null,createdDate DATE null,createdBy VARCHAR(75) null,updatedDate DATE null,updatedBy VARCHAR(75) null,flag VARCHAR(75) null,content_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table chola_shutterspeedgallery";
	public static final String ORDER_BY_JPQL = " ORDER BY shutterspeedgallery.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY chola_shutterspeedgallery.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.chola.shutterspeed.model.shutterspeedgallery"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.chola.shutterspeed.model.shutterspeedgallery"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.chola.shutterspeed.model.shutterspeedgallery"),
			true);
	public static final long CONTENT_ID_COLUMN_BITMASK = 1L;
	public static final long CREATEDDATE_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static shutterspeedgallery toModel(shutterspeedgallerySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		shutterspeedgallery model = new shutterspeedgalleryImpl();

		model.setId(soapModel.getId());
		model.setAlbumName(soapModel.getAlbumName());
		model.setAlbumDesc(soapModel.getAlbumDesc());
		model.setAlbumId(soapModel.getAlbumId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setUpdatedDate(soapModel.getUpdatedDate());
		model.setUpdatedBy(soapModel.getUpdatedBy());
		model.setFlag(soapModel.getFlag());
		model.setContent_id(soapModel.getContent_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<shutterspeedgallery> toModels(
		shutterspeedgallerySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<shutterspeedgallery> models = new ArrayList<shutterspeedgallery>(soapModels.length);

		for (shutterspeedgallerySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.chola.shutterspeed.model.shutterspeedgallery"));

	public shutterspeedgalleryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return shutterspeedgallery.class;
	}

	@Override
	public String getModelClassName() {
		return shutterspeedgallery.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("albumName", getAlbumName());
		attributes.put("albumDesc", getAlbumDesc());
		attributes.put("albumId", getAlbumId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedDate", getUpdatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("flag", getFlag());
		attributes.put("content_id", getContent_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String albumName = (String)attributes.get("albumName");

		if (albumName != null) {
			setAlbumName(albumName);
		}

		String albumDesc = (String)attributes.get("albumDesc");

		if (albumDesc != null) {
			setAlbumDesc(albumDesc);
		}

		String albumId = (String)attributes.get("albumId");

		if (albumId != null) {
			setAlbumId(albumId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		String flag = (String)attributes.get("flag");

		if (flag != null) {
			setFlag(flag);
		}

		Long content_id = (Long)attributes.get("content_id");

		if (content_id != null) {
			setContent_id(content_id);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getAlbumName() {
		if (_albumName == null) {
			return StringPool.BLANK;
		}
		else {
			return _albumName;
		}
	}

	@Override
	public void setAlbumName(String albumName) {
		_albumName = albumName;
	}

	@JSON
	@Override
	public String getAlbumDesc() {
		if (_albumDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _albumDesc;
		}
	}

	@Override
	public void setAlbumDesc(String albumDesc) {
		_albumDesc = albumDesc;
	}

	@JSON
	@Override
	public String getAlbumId() {
		if (_albumId == null) {
			return StringPool.BLANK;
		}
		else {
			return _albumId;
		}
	}

	@Override
	public void setAlbumId(String albumId) {
		_albumId = albumId;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@JSON
	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@JSON
	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@JSON
	@Override
	public String getFlag() {
		if (_flag == null) {
			return StringPool.BLANK;
		}
		else {
			return _flag;
		}
	}

	@Override
	public void setFlag(String flag) {
		_flag = flag;
	}

	@JSON
	@Override
	public long getContent_id() {
		return _content_id;
	}

	@Override
	public void setContent_id(long content_id) {
		_columnBitmask |= CONTENT_ID_COLUMN_BITMASK;

		if (!_setOriginalContent_id) {
			_setOriginalContent_id = true;

			_originalContent_id = _content_id;
		}

		_content_id = content_id;
	}

	public long getOriginalContent_id() {
		return _originalContent_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			shutterspeedgallery.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public shutterspeedgallery toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (shutterspeedgallery)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		shutterspeedgalleryImpl shutterspeedgalleryImpl = new shutterspeedgalleryImpl();

		shutterspeedgalleryImpl.setId(getId());
		shutterspeedgalleryImpl.setAlbumName(getAlbumName());
		shutterspeedgalleryImpl.setAlbumDesc(getAlbumDesc());
		shutterspeedgalleryImpl.setAlbumId(getAlbumId());
		shutterspeedgalleryImpl.setCreatedDate(getCreatedDate());
		shutterspeedgalleryImpl.setCreatedBy(getCreatedBy());
		shutterspeedgalleryImpl.setUpdatedDate(getUpdatedDate());
		shutterspeedgalleryImpl.setUpdatedBy(getUpdatedBy());
		shutterspeedgalleryImpl.setFlag(getFlag());
		shutterspeedgalleryImpl.setContent_id(getContent_id());

		shutterspeedgalleryImpl.resetOriginalValues();

		return shutterspeedgalleryImpl;
	}

	@Override
	public int compareTo(shutterspeedgallery shutterspeedgallery) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				shutterspeedgallery.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof shutterspeedgallery)) {
			return false;
		}

		shutterspeedgallery shutterspeedgallery = (shutterspeedgallery)obj;

		long primaryKey = shutterspeedgallery.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		shutterspeedgalleryModelImpl shutterspeedgalleryModelImpl = this;

		shutterspeedgalleryModelImpl._originalContent_id = shutterspeedgalleryModelImpl._content_id;

		shutterspeedgalleryModelImpl._setOriginalContent_id = false;

		shutterspeedgalleryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<shutterspeedgallery> toCacheModel() {
		shutterspeedgalleryCacheModel shutterspeedgalleryCacheModel = new shutterspeedgalleryCacheModel();

		shutterspeedgalleryCacheModel.id = getId();

		shutterspeedgalleryCacheModel.albumName = getAlbumName();

		String albumName = shutterspeedgalleryCacheModel.albumName;

		if ((albumName != null) && (albumName.length() == 0)) {
			shutterspeedgalleryCacheModel.albumName = null;
		}

		shutterspeedgalleryCacheModel.albumDesc = getAlbumDesc();

		String albumDesc = shutterspeedgalleryCacheModel.albumDesc;

		if ((albumDesc != null) && (albumDesc.length() == 0)) {
			shutterspeedgalleryCacheModel.albumDesc = null;
		}

		shutterspeedgalleryCacheModel.albumId = getAlbumId();

		String albumId = shutterspeedgalleryCacheModel.albumId;

		if ((albumId != null) && (albumId.length() == 0)) {
			shutterspeedgalleryCacheModel.albumId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			shutterspeedgalleryCacheModel.createdDate = createdDate.getTime();
		}
		else {
			shutterspeedgalleryCacheModel.createdDate = Long.MIN_VALUE;
		}

		shutterspeedgalleryCacheModel.createdBy = getCreatedBy();

		String createdBy = shutterspeedgalleryCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			shutterspeedgalleryCacheModel.createdBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			shutterspeedgalleryCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			shutterspeedgalleryCacheModel.updatedDate = Long.MIN_VALUE;
		}

		shutterspeedgalleryCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = shutterspeedgalleryCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			shutterspeedgalleryCacheModel.updatedBy = null;
		}

		shutterspeedgalleryCacheModel.flag = getFlag();

		String flag = shutterspeedgalleryCacheModel.flag;

		if ((flag != null) && (flag.length() == 0)) {
			shutterspeedgalleryCacheModel.flag = null;
		}

		shutterspeedgalleryCacheModel.content_id = getContent_id();

		return shutterspeedgalleryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", albumName=");
		sb.append(getAlbumName());
		sb.append(", albumDesc=");
		sb.append(getAlbumDesc());
		sb.append(", albumId=");
		sb.append(getAlbumId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", flag=");
		sb.append(getFlag());
		sb.append(", content_id=");
		sb.append(getContent_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.chola.shutterspeed.model.shutterspeedgallery");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>albumName</column-name><column-value><![CDATA[");
		sb.append(getAlbumName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>albumDesc</column-name><column-value><![CDATA[");
		sb.append(getAlbumDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>albumId</column-name><column-value><![CDATA[");
		sb.append(getAlbumId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flag</column-name><column-value><![CDATA[");
		sb.append(getFlag());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content_id</column-name><column-value><![CDATA[");
		sb.append(getContent_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = shutterspeedgallery.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			shutterspeedgallery.class
		};
	private long _id;
	private String _albumName;
	private String _albumDesc;
	private String _albumId;
	private Date _createdDate;
	private String _createdBy;
	private Date _updatedDate;
	private String _updatedBy;
	private String _flag;
	private long _content_id;
	private long _originalContent_id;
	private boolean _setOriginalContent_id;
	private long _columnBitmask;
	private shutterspeedgallery _escapedModel;
}