/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the businesssopDetails service. Represents a row in the &quot;chola_businesssopDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.business.model.impl.businesssopDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.business.model.impl.businesssopDetailsImpl}.
 * </p>
 *
 * @author adms.java1
 * @see businesssopDetails
 * @see com.chola.business.model.impl.businesssopDetailsImpl
 * @see com.chola.business.model.impl.businesssopDetailsModelImpl
 * @generated
 */
@ProviderType
public interface businesssopDetailsModel extends BaseModel<businesssopDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a businesssop details model instance should use the {@link businesssopDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this businesssop details.
	 *
	 * @return the primary key of this businesssop details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this businesssop details.
	 *
	 * @param primaryKey the primary key of this businesssop details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this businesssop details.
	 *
	 * @return the ID of this businesssop details
	 */
	public long getId();

	/**
	 * Sets the ID of this businesssop details.
	 *
	 * @param id the ID of this businesssop details
	 */
	public void setId(long id);

	/**
	 * Returns the businesstitle of this businesssop details.
	 *
	 * @return the businesstitle of this businesssop details
	 */
	@AutoEscape
	public String getBusinesstitle();

	/**
	 * Sets the businesstitle of this businesssop details.
	 *
	 * @param businesstitle the businesstitle of this businesssop details
	 */
	public void setBusinesstitle(String businesstitle);

	/**
	 * Returns the business desc of this businesssop details.
	 *
	 * @return the business desc of this businesssop details
	 */
	@AutoEscape
	public String getBusinessDesc();

	/**
	 * Sets the business desc of this businesssop details.
	 *
	 * @param businessDesc the business desc of this businesssop details
	 */
	public void setBusinessDesc(String businessDesc);

	/**
	 * Returns the created date of this businesssop details.
	 *
	 * @return the created date of this businesssop details
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this businesssop details.
	 *
	 * @param createdDate the created date of this businesssop details
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this businesssop details.
	 *
	 * @return the created by of this businesssop details
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this businesssop details.
	 *
	 * @param createdBy the created by of this businesssop details
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the modified date of this businesssop details.
	 *
	 * @return the modified date of this businesssop details
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this businesssop details.
	 *
	 * @param modifiedDate the modified date of this businesssop details
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this businesssop details.
	 *
	 * @return the modified by of this businesssop details
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this businesssop details.
	 *
	 * @param modifiedBy the modified by of this businesssop details
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the flag of this businesssop details.
	 *
	 * @return the flag of this businesssop details
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this businesssop details.
	 *
	 * @param flag the flag of this businesssop details
	 */
	public void setFlag(String flag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.business.model.businesssopDetails businesssopDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.business.model.businesssopDetails> toCacheModel();

	@Override
	public com.chola.business.model.businesssopDetails toEscapedModel();

	@Override
	public com.chola.business.model.businesssopDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}