/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.trainingcalendar.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the trainingcalendar service. Represents a row in the &quot;chola_trainingcalendar&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.trainingcalendar.model.impl.trainingcalendarModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.trainingcalendar.model.impl.trainingcalendarImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see trainingcalendar
 * @see com.chola.trainingcalendar.model.impl.trainingcalendarImpl
 * @see com.chola.trainingcalendar.model.impl.trainingcalendarModelImpl
 * @generated
 */
@ProviderType
public interface trainingcalendarModel extends BaseModel<trainingcalendar> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trainingcalendar model instance should use the {@link trainingcalendar} interface instead.
	 */

	/**
	 * Returns the primary key of this trainingcalendar.
	 *
	 * @return the primary key of this trainingcalendar
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trainingcalendar.
	 *
	 * @param primaryKey the primary key of this trainingcalendar
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the trainingid of this trainingcalendar.
	 *
	 * @return the trainingid of this trainingcalendar
	 */
	public long getTrainingid();

	/**
	 * Sets the trainingid of this trainingcalendar.
	 *
	 * @param trainingid the trainingid of this trainingcalendar
	 */
	public void setTrainingid(long trainingid);

	/**
	 * Returns the name of this trainingcalendar.
	 *
	 * @return the name of this trainingcalendar
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this trainingcalendar.
	 *
	 * @param name the name of this trainingcalendar
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.trainingcalendar.model.trainingcalendar trainingcalendar);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.trainingcalendar.model.trainingcalendar> toCacheModel();

	@Override
	public com.chola.trainingcalendar.model.trainingcalendar toEscapedModel();

	@Override
	public com.chola.trainingcalendar.model.trainingcalendar toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}