/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.trainingcalendar.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the trainingcalendardata service. Represents a row in the &quot;chola_trainingcalendardata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.trainingcalendar.model.impl.trainingcalendardataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.trainingcalendar.model.impl.trainingcalendardataImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see trainingcalendardata
 * @see com.chola.trainingcalendar.model.impl.trainingcalendardataImpl
 * @see com.chola.trainingcalendar.model.impl.trainingcalendardataModelImpl
 * @generated
 */
@ProviderType
public interface trainingcalendardataModel extends BaseModel<trainingcalendardata> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trainingcalendardata model instance should use the {@link trainingcalendardata} interface instead.
	 */

	/**
	 * Returns the primary key of this trainingcalendardata.
	 *
	 * @return the primary key of this trainingcalendardata
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trainingcalendardata.
	 *
	 * @param primaryKey the primary key of this trainingcalendardata
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this trainingcalendardata.
	 *
	 * @return the ID of this trainingcalendardata
	 */
	public long getId();

	/**
	 * Sets the ID of this trainingcalendardata.
	 *
	 * @param id the ID of this trainingcalendardata
	 */
	public void setId(long id);

	/**
	 * Returns the title of this trainingcalendardata.
	 *
	 * @return the title of this trainingcalendardata
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this trainingcalendardata.
	 *
	 * @param title the title of this trainingcalendardata
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this trainingcalendardata.
	 *
	 * @return the description of this trainingcalendardata
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this trainingcalendardata.
	 *
	 * @param description the description of this trainingcalendardata
	 */
	public void setDescription(String description);

	/**
	 * Returns the schedulestartdate of this trainingcalendardata.
	 *
	 * @return the schedulestartdate of this trainingcalendardata
	 */
	public Date getSchedulestartdate();

	/**
	 * Sets the schedulestartdate of this trainingcalendardata.
	 *
	 * @param schedulestartdate the schedulestartdate of this trainingcalendardata
	 */
	public void setSchedulestartdate(Date schedulestartdate);

	/**
	 * Returns the scheduleenddate of this trainingcalendardata.
	 *
	 * @return the scheduleenddate of this trainingcalendardata
	 */
	public Date getScheduleenddate();

	/**
	 * Sets the scheduleenddate of this trainingcalendardata.
	 *
	 * @param scheduleenddate the scheduleenddate of this trainingcalendardata
	 */
	public void setScheduleenddate(Date scheduleenddate);

	/**
	 * Returns the location of this trainingcalendardata.
	 *
	 * @return the location of this trainingcalendardata
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this trainingcalendardata.
	 *
	 * @param location the location of this trainingcalendardata
	 */
	public void setLocation(String location);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.trainingcalendar.model.trainingcalendardata trainingcalendardata);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.trainingcalendar.model.trainingcalendardata> toCacheModel();

	@Override
	public com.chola.trainingcalendar.model.trainingcalendardata toEscapedModel();

	@Override
	public com.chola.trainingcalendar.model.trainingcalendardata toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}