/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.trainingcalendar.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the trainingintendedtable service. Represents a row in the &quot;chola_trainingintendedtable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.trainingcalendar.model.impl.trainingintendedtableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.trainingcalendar.model.impl.trainingintendedtableImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see trainingintendedtable
 * @see com.chola.trainingcalendar.model.impl.trainingintendedtableImpl
 * @see com.chola.trainingcalendar.model.impl.trainingintendedtableModelImpl
 * @generated
 */
@ProviderType
public interface trainingintendedtableModel extends BaseModel<trainingintendedtable> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trainingintendedtable model instance should use the {@link trainingintendedtable} interface instead.
	 */

	/**
	 * Returns the primary key of this trainingintendedtable.
	 *
	 * @return the primary key of this trainingintendedtable
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trainingintendedtable.
	 *
	 * @param primaryKey the primary key of this trainingintendedtable
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this trainingintendedtable.
	 *
	 * @return the ID of this trainingintendedtable
	 */
	public long getId();

	/**
	 * Sets the ID of this trainingintendedtable.
	 *
	 * @param id the ID of this trainingintendedtable
	 */
	public void setId(long id);

	/**
	 * Returns the trainingid of this trainingintendedtable.
	 *
	 * @return the trainingid of this trainingintendedtable
	 */
	public long getTrainingid();

	/**
	 * Sets the trainingid of this trainingintendedtable.
	 *
	 * @param trainingid the trainingid of this trainingintendedtable
	 */
	public void setTrainingid(long trainingid);

	/**
	 * Returns the userid of this trainingintendedtable.
	 *
	 * @return the userid of this trainingintendedtable
	 */
	@AutoEscape
	public String getUserid();

	/**
	 * Sets the userid of this trainingintendedtable.
	 *
	 * @param userid the userid of this trainingintendedtable
	 */
	public void setUserid(String userid);

	/**
	 * Returns the screenname of this trainingintendedtable.
	 *
	 * @return the screenname of this trainingintendedtable
	 */
	@AutoEscape
	public String getScreenname();

	/**
	 * Sets the screenname of this trainingintendedtable.
	 *
	 * @param screenname the screenname of this trainingintendedtable
	 */
	public void setScreenname(String screenname);

	/**
	 * Returns the createddate of this trainingintendedtable.
	 *
	 * @return the createddate of this trainingintendedtable
	 */
	public Date getCreateddate();

	/**
	 * Sets the createddate of this trainingintendedtable.
	 *
	 * @param createddate the createddate of this trainingintendedtable
	 */
	public void setCreateddate(Date createddate);

	/**
	 * Returns the flag of this trainingintendedtable.
	 *
	 * @return the flag of this trainingintendedtable
	 */
	public int getFlag();

	/**
	 * Sets the flag of this trainingintendedtable.
	 *
	 * @param flag the flag of this trainingintendedtable
	 */
	public void setFlag(int flag);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.trainingcalendar.model.trainingintendedtable trainingintendedtable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.trainingcalendar.model.trainingintendedtable> toCacheModel();

	@Override
	public com.chola.trainingcalendar.model.trainingintendedtable toEscapedModel();

	@Override
	public com.chola.trainingcalendar.model.trainingintendedtable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}