/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.trainingcalendar.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the trainingpersonalisedparameterscontentstore service. Represents a row in the &quot;chola_trainingpersonalisedparameterscontentstore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.trainingcalendar.model.impl.trainingpersonalisedparameterscontentstoreModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.trainingcalendar.model.impl.trainingpersonalisedparameterscontentstoreImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see trainingpersonalisedparameterscontentstore
 * @see com.chola.trainingcalendar.model.impl.trainingpersonalisedparameterscontentstoreImpl
 * @see com.chola.trainingcalendar.model.impl.trainingpersonalisedparameterscontentstoreModelImpl
 * @generated
 */
@ProviderType
public interface trainingpersonalisedparameterscontentstoreModel
	extends BaseModel<trainingpersonalisedparameterscontentstore> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trainingpersonalisedparameterscontentstore model instance should use the {@link trainingpersonalisedparameterscontentstore} interface instead.
	 */

	/**
	 * Returns the primary key of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the primary key of this trainingpersonalisedparameterscontentstore
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param primaryKey the primary key of this trainingpersonalisedparameterscontentstore
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the ID of this trainingpersonalisedparameterscontentstore
	 */
	public long getId();

	/**
	 * Sets the ID of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param id the ID of this trainingpersonalisedparameterscontentstore
	 */
	public void setId(long id);

	/**
	 * Returns the content_id of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the content_id of this trainingpersonalisedparameterscontentstore
	 */
	public long getContent_id();

	/**
	 * Sets the content_id of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param content_id the content_id of this trainingpersonalisedparameterscontentstore
	 */
	public void setContent_id(long content_id);

	/**
	 * Returns the business of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the business of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getBusiness();

	/**
	 * Sets the business of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param business the business of this trainingpersonalisedparameterscontentstore
	 */
	public void setBusiness(String business);

	/**
	 * Returns the unit of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the unit of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param unit the unit of this trainingpersonalisedparameterscontentstore
	 */
	public void setUnit(String unit);

	/**
	 * Returns the function of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the function of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getFunction();

	/**
	 * Sets the function of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param function the function of this trainingpersonalisedparameterscontentstore
	 */
	public void setFunction(String function);

	/**
	 * Returns the department of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the department of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param department the department of this trainingpersonalisedparameterscontentstore
	 */
	public void setDepartment(String department);

	/**
	 * Returns the designation of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the designation of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param designation the designation of this trainingpersonalisedparameterscontentstore
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the product of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the product of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param product the product of this trainingpersonalisedparameterscontentstore
	 */
	public void setProduct(String product);

	/**
	 * Returns the zone of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the zone of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getZone();

	/**
	 * Sets the zone of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param zone the zone of this trainingpersonalisedparameterscontentstore
	 */
	public void setZone(String zone);

	/**
	 * Returns the branch of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the branch of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getBranch();

	/**
	 * Sets the branch of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param branch the branch of this trainingpersonalisedparameterscontentstore
	 */
	public void setBranch(String branch);

	/**
	 * Returns the grade of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the grade of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param grade the grade of this trainingpersonalisedparameterscontentstore
	 */
	public void setGrade(String grade);

	/**
	 * Returns the region of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the region of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param region the region of this trainingpersonalisedparameterscontentstore
	 */
	public void setRegion(String region);

	/**
	 * Returns the location of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the location of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param location the location of this trainingpersonalisedparameterscontentstore
	 */
	public void setLocation(String location);

	/**
	 * Returns the user_id of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the user_id of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getUser_id();

	/**
	 * Sets the user_id of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param user_id the user_id of this trainingpersonalisedparameterscontentstore
	 */
	public void setUser_id(String user_id);

	/**
	 * Returns the gender of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the gender of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param gender the gender of this trainingpersonalisedparameterscontentstore
	 */
	public void setGender(String gender);

	/**
	 * Returns the age_type of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the age_type of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getAge_type();

	/**
	 * Sets the age_type of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param age_type the age_type of this trainingpersonalisedparameterscontentstore
	 */
	public void setAge_type(String age_type);

	/**
	 * Returns the age_value of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the age_value of this trainingpersonalisedparameterscontentstore
	 */
	@AutoEscape
	public String getAge_value();

	/**
	 * Sets the age_value of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param age_value the age_value of this trainingpersonalisedparameterscontentstore
	 */
	public void setAge_value(String age_value);

	/**
	 * Returns the notification_type of this trainingpersonalisedparameterscontentstore.
	 *
	 * @return the notification_type of this trainingpersonalisedparameterscontentstore
	 */
	public long getNotification_type();

	/**
	 * Sets the notification_type of this trainingpersonalisedparameterscontentstore.
	 *
	 * @param notification_type the notification_type of this trainingpersonalisedparameterscontentstore
	 */
	public void setNotification_type(long notification_type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.trainingcalendar.model.trainingpersonalisedparameterscontentstore trainingpersonalisedparameterscontentstore);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.trainingcalendar.model.trainingpersonalisedparameterscontentstore> toCacheModel();

	@Override
	public com.chola.trainingcalendar.model.trainingpersonalisedparameterscontentstore toEscapedModel();

	@Override
	public com.chola.trainingcalendar.model.trainingpersonalisedparameterscontentstore toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}