/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.news.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Around_World service. Represents a row in the &quot;cholaA_Around_World&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.news.model.impl.Around_WorldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.news.model.impl.Around_WorldImpl}.
 * </p>
 *
 * @author adms.java1
 * @see Around_World
 * @see com.chola.news.model.impl.Around_WorldImpl
 * @see com.chola.news.model.impl.Around_WorldModelImpl
 * @generated
 */
@ProviderType
public interface Around_WorldModel extends BaseModel<Around_World> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a around_ world model instance should use the {@link Around_World} interface instead.
	 */

	/**
	 * Returns the primary key of this around_ world.
	 *
	 * @return the primary key of this around_ world
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this around_ world.
	 *
	 * @param primaryKey the primary key of this around_ world
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this around_ world.
	 *
	 * @return the ID of this around_ world
	 */
	public long getId();

	/**
	 * Sets the ID of this around_ world.
	 *
	 * @param id the ID of this around_ world
	 */
	public void setId(long id);

	/**
	 * Returns the news of this around_ world.
	 *
	 * @return the news of this around_ world
	 */
	@AutoEscape
	public String getNews();

	/**
	 * Sets the news of this around_ world.
	 *
	 * @param news the news of this around_ world
	 */
	public void setNews(String news);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Around_World around_World);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Around_World> toCacheModel();

	@Override
	public Around_World toEscapedModel();

	@Override
	public Around_World toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}