/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.book.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the bookpath service. Represents a row in the &quot;chola_bookpath&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.book.model.impl.bookpathModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.book.model.impl.bookpathImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see bookpath
 * @see com.chola.book.model.impl.bookpathImpl
 * @see com.chola.book.model.impl.bookpathModelImpl
 * @generated
 */
@ProviderType
public interface bookpathModel extends BaseModel<bookpath> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bookpath model instance should use the {@link bookpath} interface instead.
	 */

	/**
	 * Returns the primary key of this bookpath.
	 *
	 * @return the primary key of this bookpath
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bookpath.
	 *
	 * @param primaryKey the primary key of this bookpath
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this bookpath.
	 *
	 * @return the ID of this bookpath
	 */
	public long getId();

	/**
	 * Sets the ID of this bookpath.
	 *
	 * @param id the ID of this bookpath
	 */
	public void setId(long id);

	/**
	 * Returns the book of this bookpath.
	 *
	 * @return the book of this bookpath
	 */
	@AutoEscape
	public String getBook();

	/**
	 * Sets the book of this bookpath.
	 *
	 * @param book the book of this bookpath
	 */
	public void setBook(String book);

	/**
	 * Returns the bookpath of this bookpath.
	 *
	 * @return the bookpath of this bookpath
	 */
	@AutoEscape
	public String getBookpath();

	/**
	 * Sets the bookpath of this bookpath.
	 *
	 * @param bookpath the bookpath of this bookpath
	 */
	public void setBookpath(String bookpath);

	/**
	 * Returns the createddate of this bookpath.
	 *
	 * @return the createddate of this bookpath
	 */
	public Date getCreateddate();

	/**
	 * Sets the createddate of this bookpath.
	 *
	 * @param createddate the createddate of this bookpath
	 */
	public void setCreateddate(Date createddate);

	/**
	 * Returns the createdby of this bookpath.
	 *
	 * @return the createdby of this bookpath
	 */
	@AutoEscape
	public String getCreatedby();

	/**
	 * Sets the createdby of this bookpath.
	 *
	 * @param createdby the createdby of this bookpath
	 */
	public void setCreatedby(String createdby);

	/**
	 * Returns the flag of this bookpath.
	 *
	 * @return the flag of this bookpath
	 */
	@AutoEscape
	public String getFlag();

	/**
	 * Sets the flag of this bookpath.
	 *
	 * @param flag the flag of this bookpath
	 */
	public void setFlag(String flag);

	/**
	 * Returns the book_id of this bookpath.
	 *
	 * @return the book_id of this bookpath
	 */
	public long getBook_id();

	/**
	 * Sets the book_id of this bookpath.
	 *
	 * @param book_id the book_id of this bookpath
	 */
	public void setBook_id(long book_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.chola.book.model.bookpath bookpath);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.book.model.bookpath> toCacheModel();

	@Override
	public com.chola.book.model.bookpath toEscapedModel();

	@Override
	public com.chola.book.model.bookpath toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}