/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.businessmis.service.base;

import com.chola.businessmis.model.businessmisusers;
import com.chola.businessmis.service.businessmisusersService;
import com.chola.businessmis.service.persistence.businessmisdetailsFinder;
import com.chola.businessmis.service.persistence.businessmisdetailsPersistence;
import com.chola.businessmis.service.persistence.businessmisusersPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the businessmisusers remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.chola.businessmis.service.impl.businessmisusersServiceImpl}.
 * </p>
 *
 * @author CloverLiferay01
 * @see com.chola.businessmis.service.impl.businessmisusersServiceImpl
 * @see com.chola.businessmis.service.businessmisusersServiceUtil
 * @generated
 */
public abstract class businessmisusersServiceBaseImpl extends BaseServiceImpl
	implements businessmisusersService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.chola.businessmis.service.businessmisusersServiceUtil} to access the businessmisusers remote service.
	 */

	/**
	 * Returns the businessmisdetails local service.
	 *
	 * @return the businessmisdetails local service
	 */
	public com.chola.businessmis.service.businessmisdetailsLocalService getbusinessmisdetailsLocalService() {
		return businessmisdetailsLocalService;
	}

	/**
	 * Sets the businessmisdetails local service.
	 *
	 * @param businessmisdetailsLocalService the businessmisdetails local service
	 */
	public void setbusinessmisdetailsLocalService(
		com.chola.businessmis.service.businessmisdetailsLocalService businessmisdetailsLocalService) {
		this.businessmisdetailsLocalService = businessmisdetailsLocalService;
	}

	/**
	 * Returns the businessmisdetails remote service.
	 *
	 * @return the businessmisdetails remote service
	 */
	public com.chola.businessmis.service.businessmisdetailsService getbusinessmisdetailsService() {
		return businessmisdetailsService;
	}

	/**
	 * Sets the businessmisdetails remote service.
	 *
	 * @param businessmisdetailsService the businessmisdetails remote service
	 */
	public void setbusinessmisdetailsService(
		com.chola.businessmis.service.businessmisdetailsService businessmisdetailsService) {
		this.businessmisdetailsService = businessmisdetailsService;
	}

	/**
	 * Returns the businessmisdetails persistence.
	 *
	 * @return the businessmisdetails persistence
	 */
	public businessmisdetailsPersistence getbusinessmisdetailsPersistence() {
		return businessmisdetailsPersistence;
	}

	/**
	 * Sets the businessmisdetails persistence.
	 *
	 * @param businessmisdetailsPersistence the businessmisdetails persistence
	 */
	public void setbusinessmisdetailsPersistence(
		businessmisdetailsPersistence businessmisdetailsPersistence) {
		this.businessmisdetailsPersistence = businessmisdetailsPersistence;
	}

	/**
	 * Returns the businessmisdetails finder.
	 *
	 * @return the businessmisdetails finder
	 */
	public businessmisdetailsFinder getbusinessmisdetailsFinder() {
		return businessmisdetailsFinder;
	}

	/**
	 * Sets the businessmisdetails finder.
	 *
	 * @param businessmisdetailsFinder the businessmisdetails finder
	 */
	public void setbusinessmisdetailsFinder(
		businessmisdetailsFinder businessmisdetailsFinder) {
		this.businessmisdetailsFinder = businessmisdetailsFinder;
	}

	/**
	 * Returns the businessmisusers local service.
	 *
	 * @return the businessmisusers local service
	 */
	public com.chola.businessmis.service.businessmisusersLocalService getbusinessmisusersLocalService() {
		return businessmisusersLocalService;
	}

	/**
	 * Sets the businessmisusers local service.
	 *
	 * @param businessmisusersLocalService the businessmisusers local service
	 */
	public void setbusinessmisusersLocalService(
		com.chola.businessmis.service.businessmisusersLocalService businessmisusersLocalService) {
		this.businessmisusersLocalService = businessmisusersLocalService;
	}

	/**
	 * Returns the businessmisusers remote service.
	 *
	 * @return the businessmisusers remote service
	 */
	public businessmisusersService getbusinessmisusersService() {
		return businessmisusersService;
	}

	/**
	 * Sets the businessmisusers remote service.
	 *
	 * @param businessmisusersService the businessmisusers remote service
	 */
	public void setbusinessmisusersService(
		businessmisusersService businessmisusersService) {
		this.businessmisusersService = businessmisusersService;
	}

	/**
	 * Returns the businessmisusers persistence.
	 *
	 * @return the businessmisusers persistence
	 */
	public businessmisusersPersistence getbusinessmisusersPersistence() {
		return businessmisusersPersistence;
	}

	/**
	 * Sets the businessmisusers persistence.
	 *
	 * @param businessmisusersPersistence the businessmisusers persistence
	 */
	public void setbusinessmisusersPersistence(
		businessmisusersPersistence businessmisusersPersistence) {
		this.businessmisusersPersistence = businessmisusersPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return businessmisusersService.class.getName();
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return businessmisusers.class;
	}

	protected String getModelClassName() {
		return businessmisusers.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = businessmisusersPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.chola.businessmis.service.businessmisdetailsLocalService.class)
	protected com.chola.businessmis.service.businessmisdetailsLocalService businessmisdetailsLocalService;
	@BeanReference(type = com.chola.businessmis.service.businessmisdetailsService.class)
	protected com.chola.businessmis.service.businessmisdetailsService businessmisdetailsService;
	@BeanReference(type = businessmisdetailsPersistence.class)
	protected businessmisdetailsPersistence businessmisdetailsPersistence;
	@BeanReference(type = businessmisdetailsFinder.class)
	protected businessmisdetailsFinder businessmisdetailsFinder;
	@BeanReference(type = com.chola.businessmis.service.businessmisusersLocalService.class)
	protected com.chola.businessmis.service.businessmisusersLocalService businessmisusersLocalService;
	@BeanReference(type = businessmisusersService.class)
	protected businessmisusersService businessmisusersService;
	@BeanReference(type = businessmisusersPersistence.class)
	protected businessmisusersPersistence businessmisusersPersistence;
	@BeanReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private ClassLoader _classLoader;
	private businessmisusersServiceClpInvoker _clpInvoker = new businessmisusersServiceClpInvoker();
}