/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.usertheme.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.usertheme.model.themecolor;
import com.usertheme.model.themecolorModel;
import com.usertheme.model.themecolorSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the themecolor service. Represents a row in the &quot;usertheme_themecolor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link themecolorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link themecolorImpl}.
 * </p>
 *
 * @author CloverLiferay02
 * @see themecolorImpl
 * @see themecolor
 * @see themecolorModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class themecolorModelImpl extends BaseModelImpl<themecolor>
	implements themecolorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a themecolor model instance should use the {@link themecolor} interface instead.
	 */
	public static final String TABLE_NAME = "usertheme_themecolor";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "user_id", Types.VARCHAR },
			{ "color", Types.VARCHAR },
			{ "updatedDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("user_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("color", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("updatedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table usertheme_themecolor (id_ LONG not null primary key,user_id VARCHAR(75) null,color VARCHAR(75) null,updatedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table usertheme_themecolor";
	public static final String ORDER_BY_JPQL = " ORDER BY themecolor.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY usertheme_themecolor.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.usertheme.model.themecolor"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.usertheme.model.themecolor"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.usertheme.model.themecolor"),
			true);
	public static final long USER_ID_COLUMN_BITMASK = 1L;
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static themecolor toModel(themecolorSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		themecolor model = new themecolorImpl();

		model.setId(soapModel.getId());
		model.setUser_id(soapModel.getUser_id());
		model.setColor(soapModel.getColor());
		model.setUpdatedDate(soapModel.getUpdatedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<themecolor> toModels(themecolorSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<themecolor> models = new ArrayList<themecolor>(soapModels.length);

		for (themecolorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.usertheme.model.themecolor"));

	public themecolorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return themecolor.class;
	}

	@Override
	public String getModelClassName() {
		return themecolor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("user_id", getUser_id());
		attributes.put("color", getColor());
		attributes.put("updatedDate", getUpdatedDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String user_id = (String)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		String color = (String)attributes.get("color");

		if (color != null) {
			setColor(color);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getUser_id() {
		if (_user_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _user_id;
		}
	}

	@Override
	public void setUser_id(String user_id) {
		_columnBitmask |= USER_ID_COLUMN_BITMASK;

		if (_originalUser_id == null) {
			_originalUser_id = _user_id;
		}

		_user_id = user_id;
	}

	public String getOriginalUser_id() {
		return GetterUtil.getString(_originalUser_id);
	}

	@JSON
	@Override
	public String getColor() {
		if (_color == null) {
			return StringPool.BLANK;
		}
		else {
			return _color;
		}
	}

	@Override
	public void setColor(String color) {
		_color = color;
	}

	@JSON
	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			themecolor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public themecolor toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (themecolor)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		themecolorImpl themecolorImpl = new themecolorImpl();

		themecolorImpl.setId(getId());
		themecolorImpl.setUser_id(getUser_id());
		themecolorImpl.setColor(getColor());
		themecolorImpl.setUpdatedDate(getUpdatedDate());

		themecolorImpl.resetOriginalValues();

		return themecolorImpl;
	}

	@Override
	public int compareTo(themecolor themecolor) {
		long primaryKey = themecolor.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof themecolor)) {
			return false;
		}

		themecolor themecolor = (themecolor)obj;

		long primaryKey = themecolor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		themecolorModelImpl themecolorModelImpl = this;

		themecolorModelImpl._originalUser_id = themecolorModelImpl._user_id;

		themecolorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<themecolor> toCacheModel() {
		themecolorCacheModel themecolorCacheModel = new themecolorCacheModel();

		themecolorCacheModel.id = getId();

		themecolorCacheModel.user_id = getUser_id();

		String user_id = themecolorCacheModel.user_id;

		if ((user_id != null) && (user_id.length() == 0)) {
			themecolorCacheModel.user_id = null;
		}

		themecolorCacheModel.color = getColor();

		String color = themecolorCacheModel.color;

		if ((color != null) && (color.length() == 0)) {
			themecolorCacheModel.color = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			themecolorCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			themecolorCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return themecolorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", color=");
		sb.append(getColor());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.usertheme.model.themecolor");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>color</column-name><column-value><![CDATA[");
		sb.append(getColor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = themecolor.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			themecolor.class
		};
	private long _id;
	private String _user_id;
	private String _originalUser_id;
	private String _color;
	private Date _updatedDate;
	private long _columnBitmask;
	private themecolor _escapedModel;
}