/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.topsearch.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TopSearch service. Represents a row in the &quot;master_TopSearch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.topsearch.model.impl.TopSearchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.topsearch.model.impl.TopSearchImpl}.
 * </p>
 *
 * @author adms.java1
 * @see TopSearch
 * @see com.chola.topsearch.model.impl.TopSearchImpl
 * @see com.chola.topsearch.model.impl.TopSearchModelImpl
 * @generated
 */
@ProviderType
public interface TopSearchModel extends BaseModel<TopSearch> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a top search model instance should use the {@link TopSearch} interface instead.
	 */

	/**
	 * Returns the primary key of this top search.
	 *
	 * @return the primary key of this top search
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this top search.
	 *
	 * @param primaryKey the primary key of this top search
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the srch ID of this top search.
	 *
	 * @return the srch ID of this top search
	 */
	public long getSrchId();

	/**
	 * Sets the srch ID of this top search.
	 *
	 * @param srchId the srch ID of this top search
	 */
	public void setSrchId(long srchId);

	/**
	 * Returns the name of this top search.
	 *
	 * @return the name of this top search
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this top search.
	 *
	 * @param Name the name of this top search
	 */
	public void setName(String Name);

	/**
	 * Returns the create date of this top search.
	 *
	 * @return the create date of this top search
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this top search.
	 *
	 * @param createDate the create date of this top search
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this top search.
	 *
	 * @return the modified date of this top search
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this top search.
	 *
	 * @param modifiedDate the modified date of this top search
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TopSearch topSearch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TopSearch> toCacheModel();

	@Override
	public TopSearch toEscapedModel();

	@Override
	public TopSearch toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}