/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the mapping service. Represents a row in the &quot;Branch_mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.model.impl.mappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.model.impl.mappingImpl}.
 * </p>
 *
 * @author adms.java1
 * @see mapping
 * @see com.model.impl.mappingImpl
 * @see com.model.impl.mappingModelImpl
 * @generated
 */
@ProviderType
public interface mappingModel extends BaseModel<mapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mapping model instance should use the {@link mapping} interface instead.
	 */

	/**
	 * Returns the primary key of this mapping.
	 *
	 * @return the primary key of this mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mapping.
	 *
	 * @param primaryKey the primary key of this mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mapping_id of this mapping.
	 *
	 * @return the mapping_id of this mapping
	 */
	public long getMapping_id();

	/**
	 * Sets the mapping_id of this mapping.
	 *
	 * @param mapping_id the mapping_id of this mapping
	 */
	public void setMapping_id(long mapping_id);

	/**
	 * Returns the product_id of this mapping.
	 *
	 * @return the product_id of this mapping
	 */
	public long getProduct_id();

	/**
	 * Sets the product_id of this mapping.
	 *
	 * @param product_id the product_id of this mapping
	 */
	public void setProduct_id(long product_id);

	/**
	 * Returns the state_id of this mapping.
	 *
	 * @return the state_id of this mapping
	 */
	public long getState_id();

	/**
	 * Sets the state_id of this mapping.
	 *
	 * @param state_id the state_id of this mapping
	 */
	public void setState_id(long state_id);

	/**
	 * Returns the city_id of this mapping.
	 *
	 * @return the city_id of this mapping
	 */
	public long getCity_id();

	/**
	 * Sets the city_id of this mapping.
	 *
	 * @param city_id the city_id of this mapping
	 */
	public void setCity_id(long city_id);

	/**
	 * Returns the branch_id of this mapping.
	 *
	 * @return the branch_id of this mapping
	 */
	public long getBranch_id();

	/**
	 * Sets the branch_id of this mapping.
	 *
	 * @param branch_id the branch_id of this mapping
	 */
	public void setBranch_id(long branch_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.model.mapping mapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.model.mapping> toCacheModel();

	@Override
	public com.model.mapping toEscapedModel();

	@Override
	public com.model.mapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}