/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.chola.conferenceroombooking.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the conferenceroombookingdetails service. Represents a row in the &quot;branch_conferenceroombookingdetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.chola.conferenceroombooking.model.impl.conferenceroombookingdetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.chola.conferenceroombooking.model.impl.conferenceroombookingdetailsImpl}.
 * </p>
 *
 * @author adms.java1
 * @see conferenceroombookingdetails
 * @see com.chola.conferenceroombooking.model.impl.conferenceroombookingdetailsImpl
 * @see com.chola.conferenceroombooking.model.impl.conferenceroombookingdetailsModelImpl
 * @generated
 */
@ProviderType
public interface conferenceroombookingdetailsModel extends BaseModel<conferenceroombookingdetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a conferenceroombookingdetails model instance should use the {@link conferenceroombookingdetails} interface instead.
	 */

	/**
	 * Returns the primary key of this conferenceroombookingdetails.
	 *
	 * @return the primary key of this conferenceroombookingdetails
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this conferenceroombookingdetails.
	 *
	 * @param primaryKey the primary key of this conferenceroombookingdetails
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bookid of this conferenceroombookingdetails.
	 *
	 * @return the bookid of this conferenceroombookingdetails
	 */
	public long getBookid();

	/**
	 * Sets the bookid of this conferenceroombookingdetails.
	 *
	 * @param bookid the bookid of this conferenceroombookingdetails
	 */
	public void setBookid(long bookid);

	/**
	 * Returns the startdate of this conferenceroombookingdetails.
	 *
	 * @return the startdate of this conferenceroombookingdetails
	 */
	public Date getStartdate();

	/**
	 * Sets the startdate of this conferenceroombookingdetails.
	 *
	 * @param startdate the startdate of this conferenceroombookingdetails
	 */
	public void setStartdate(Date startdate);

	/**
	 * Returns the startime of this conferenceroombookingdetails.
	 *
	 * @return the startime of this conferenceroombookingdetails
	 */
	@AutoEscape
	public String getStartime();

	/**
	 * Sets the startime of this conferenceroombookingdetails.
	 *
	 * @param startime the startime of this conferenceroombookingdetails
	 */
	public void setStartime(String startime);

	/**
	 * Returns the endtime of this conferenceroombookingdetails.
	 *
	 * @return the endtime of this conferenceroombookingdetails
	 */
	@AutoEscape
	public String getEndtime();

	/**
	 * Sets the endtime of this conferenceroombookingdetails.
	 *
	 * @param endtime the endtime of this conferenceroombookingdetails
	 */
	public void setEndtime(String endtime);

	/**
	 * Returns the roomid of this conferenceroombookingdetails.
	 *
	 * @return the roomid of this conferenceroombookingdetails
	 */
	public int getRoomid();

	/**
	 * Sets the roomid of this conferenceroombookingdetails.
	 *
	 * @param roomid the roomid of this conferenceroombookingdetails
	 */
	public void setRoomid(int roomid);

	/**
	 * Returns the meeting_emailid of this conferenceroombookingdetails.
	 *
	 * @return the meeting_emailid of this conferenceroombookingdetails
	 */
	@AutoEscape
	public String getMeeting_emailid();

	/**
	 * Sets the meeting_emailid of this conferenceroombookingdetails.
	 *
	 * @param meeting_emailid the meeting_emailid of this conferenceroombookingdetails
	 */
	public void setMeeting_emailid(String meeting_emailid);

	/**
	 * Returns the meeting_title of this conferenceroombookingdetails.
	 *
	 * @return the meeting_title of this conferenceroombookingdetails
	 */
	@AutoEscape
	public String getMeeting_title();

	/**
	 * Sets the meeting_title of this conferenceroombookingdetails.
	 *
	 * @param meeting_title the meeting_title of this conferenceroombookingdetails
	 */
	public void setMeeting_title(String meeting_title);

	/**
	 * Returns the meeting_agenda of this conferenceroombookingdetails.
	 *
	 * @return the meeting_agenda of this conferenceroombookingdetails
	 */
	@AutoEscape
	public String getMeeting_agenda();

	/**
	 * Sets the meeting_agenda of this conferenceroombookingdetails.
	 *
	 * @param meeting_agenda the meeting_agenda of this conferenceroombookingdetails
	 */
	public void setMeeting_agenda(String meeting_agenda);

	/**
	 * Returns the status of this conferenceroombookingdetails.
	 *
	 * @return the status of this conferenceroombookingdetails
	 */
	public int getStatus();

	/**
	 * Sets the status of this conferenceroombookingdetails.
	 *
	 * @param status the status of this conferenceroombookingdetails
	 */
	public void setStatus(int status);

	/**
	 * Returns the userid of this conferenceroombookingdetails.
	 *
	 * @return the userid of this conferenceroombookingdetails
	 */
	public long getUserid();

	/**
	 * Sets the userid of this conferenceroombookingdetails.
	 *
	 * @param userid the userid of this conferenceroombookingdetails
	 */
	public void setUserid(long userid);

	/**
	 * Returns the username of this conferenceroombookingdetails.
	 *
	 * @return the username of this conferenceroombookingdetails
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this conferenceroombookingdetails.
	 *
	 * @param username the username of this conferenceroombookingdetails
	 */
	public void setUsername(String username);

	/**
	 * Returns the createdate of this conferenceroombookingdetails.
	 *
	 * @return the createdate of this conferenceroombookingdetails
	 */
	public Date getCreatedate();

	/**
	 * Sets the createdate of this conferenceroombookingdetails.
	 *
	 * @param createdate the createdate of this conferenceroombookingdetails
	 */
	public void setCreatedate(Date createdate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.chola.conferenceroombooking.model.conferenceroombookingdetails conferenceroombookingdetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.chola.conferenceroombooking.model.conferenceroombookingdetails> toCacheModel();

	@Override
	public com.chola.conferenceroombooking.model.conferenceroombookingdetails toEscapedModel();

	@Override
	public com.chola.conferenceroombooking.model.conferenceroombookingdetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}